Repository ImanYZ/1Cademy-Public, pull requests merged in 2022-11, with the labels that each got.

#450 Tag list state was being replaced
  src/hooks/useTagsTreeView.ts
Labels: bug

#469 Improvements from Develop
  package-lock.json
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/global.css
  src/hooks/useTagsTreeView.ts
  src/pages/dashboard.tsx
Labels: bug, enhancement

#481 fixed proposal improvement bug on change title
  src/utils/version-helpers.ts
Labels: bug

#482 Improvement from Develop
  src/components/instructors/HeaderNavbar.tsx
  src/components/instructors/SemesterFilter.tsx
  src/components/instructors/useSemesterFilter.ts
  src/components/layouts/InstructorsLayout.tsx
  src/components/map/CommunityLeaderboard/CommunityLeaderboard.tsx
  src/components/map/Modal/Modal.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/global.css
  src/pages/dashboard.tsx
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/tmp.tsx
  src/styles/ComLeaderboard.css
  src/styles/app.css
  src/utils/version-helpers.ts
Labels: bug, enhancement

#483 Edge case test for proposalNodeImprovement api
  __tests__/pages/api/proposeNodeImprovement.test.ts
Labels: enhancement, test

#467 If you're authenticated, opening a node page should go to your dashboard, then change your sNode to the node in the URL and scroll to that node.
  src/pages/dashboard.tsx
  src/pages/node/[title]/[id].tsx
Labels: bug, enhancement

#493 Notebook search error fixed
  src/middlewares/fbAuth.ts
  src/pages/api/searchNodesInNotebook.ts
  src/utils/arrayToChunks.ts
Labels: bug

#502 proposal reason reset
  src/components/map/Node.tsx
  src/pages/dashboard.tsx
Labels: bug

#503 Improvements from Develop
  __tests__/pages/api/proposeNodeImprovement.test.ts
  package-lock.json
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/Sidebar/SearchList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/components/map/UserStatusIcon.tsx
  src/components/map/UserStatusSettings.tsx
  src/global.css
  src/middlewares/fbAuth.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/dashboard.tsx
  src/pages/node/[title]/[id].tsx
  src/utils/arrayToChunks.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#510 Improvements from Develop
  src/components/SignUpPersonalInfo.tsx
  src/components/instructors/HeaderNavbar.tsx
  src/components/instructors/HeaderNavbarMovil.tsx
  src/components/instructors/SemesterFilter.tsx
  src/components/layouts/InstructorsLayout.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/Sidebar/BookmarksList.tsx
  src/components/map/Sidebar/Citations.tsx
  src/components/map/Sidebar/SearchList.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/context/AuthContext.tsx
  src/pages/dashboard.tsx
  src/pages/instructors/settings.tsx
  src/pages/instructors/students.tsx
  src/pages/node/[title]/[id].tsx
  src/pages/signup.tsx
Labels: enhancement

#515 instructor signup and settings
  package.json
  src/components/map/Node.tsx
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/pages/api/instructor/students/[semesterId]/signup.ts
  src/pages/dashboard.tsx
  src/types/ICourse.ts
  src/types/INode.ts
  src/types/IUser.ts
  src/utils/instructor.ts
  src/utils/signalAllUserNodesChanges.ts
  src/utils/version-helpers.ts
  src/workers/MapWorker.ts
  testUtils/fakers/node.ts
Labels: enhancement

#520 package-lock.json update for CI
  package-lock.json
Labels: bug

#517 Improvements from Develop
  package-lock.json
  package.json
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/ProposalsList/ProposalItem/ProposalItem.tsx
  src/components/map/ProposalsList/ProposalsList.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/pages/api/instructor/students/[semesterId]/signup.ts
  src/pages/dashboard.tsx
  src/types/ICourse.ts
  src/types/INode.ts
  src/types/IUser.ts
  src/utils/instructor.ts
  src/utils/signalAllUserNodesChanges.ts
  src/utils/version-helpers.ts
  src/workers/MapWorker.ts
  testUtils/fakers/node.ts
Labels: bug, enhancement

#522 fix issues in the Toolbar sidebar a unnecessary scroll is appearing
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
Labels: bug

#523 settings api tests added and bug fixed in instructor settings api
  __tests__/pages/api/instructor/students/[semesterId]/setting.test.ts
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/pages/api/instructor/students/[semesterId]/signup.ts
  src/types/ICourse.ts
  testUtils/fakers/course.ts
Labels: bug, test

#525 Improvements from Develop
  __tests__/pages/api/instructor/students/[semesterId]/setting.test.ts
  src/components/map/Sidebar/NotificationsList.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/pages/api/instructor/students/[semesterId]/signup.ts
  src/pages/dashboard.tsx
  src/types/ICourse.ts
  testUtils/fakers/course.ts
Labels: bug, enhancement, test

#527 missing markdown markup
  src/pages/api/instructor/students/[semesterId]/setting.ts
Labels: bug

#545 postfix semester title in node titles
  __tests__/pages/api/instructor/students/[semesterId]/setting.test.ts
  src/pages/api/instructor/students/[semesterId]/setting.ts
Labels: bug, enhancement

#547 Setting api bug fix to create nested children even if parent exists
  src/pages/api/instructor/students/[semesterId]/setting.ts
Labels: bug

#548 added custom claim for students in sign up
  src/pages/api/instructor/students/[semesterId]/signup.ts
  src/types/ICourse.ts
Labels: enhancement

#550 signup api tests
  __tests__/pages/api/instructor/students/[semesterId]/signup.test.ts
  src/pages/api/instructor/students/[semesterId]/signup.ts
Labels: test

#555 instructor create course api and minor tests
  __tests__/pages/api/instructor/create.test.ts
  src/pages/api/instructor/course/create.ts
Labels: enhancement

#562 Usernodes and Versions setup in course settings and course students api
  __tests__/pages/api/instructor/create.test.ts
  __tests__/pages/api/instructor/students/[semesterId]/setting.test.ts
  src/pages/api/instructor/course/create.ts
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/types/INodeVersion.ts
Labels: enhancement

#585 Align the semester and courses' buttons on top of the instructor students page.
  src/pages/instructors/students.tsx
Labels: bug

#589 Add who the student is when hovering on each bubble in the plot
  src/components/chats/BubbleChart.tsx
  src/pages/instructors/dashboard.tsx
Labels: bug

#591 add the mouse out to the bubble chart showing the student belonging
  src/components/chats/BubbleChart.tsx
Labels: bug

#599 Added validation in some fields of instructor settings page
  src/components/instructors/setting/Proposal.tsx
  src/pages/instructors/settings.tsx
Labels: enhancement

#602 delete course api for instructor
  __tests__/pages/api/instructor/course/[semesterId]/delete.test.ts
  __tests__/pages/api/instructor/course/create.test.ts
  __tests__/pages/api/instructor/students/[semesterId]/setting.test.ts
  src/pages/api/instructor/course/[semesterId]/delete.ts
  src/utils/getAllUserNodes.ts
  src/utils/instructor.ts
  src/utils/retrieveAndsignalAllUserNodesChanges.ts
Labels: enhancement

#613 make some improvement and fix styles in the students page
  src/pages/instructors/students.tsx
Labels: enhancement

#617 implemented deleteNode and added chapters as children of semester
  src/pages/api/instructor/students/[semesterId]/setting.ts
Labels: bug, enhancement

#634 Usernodes visibility fixed on Dashboard
  src/pages/dashboard.tsx
Labels: bug

#643 fix issues in the student page and add a verification for deleting students from a course
  src/components/DeleteButton.tsx
  src/components/instructors/Drawers/StudentFilters.tsx
  src/pages/instructors/students.tsx
Labels: bug, enhancement

#646 Task/457 edit course syllabus
  package-lock.json
  src/pages/api/checkTag.ts
  src/types/ICourse.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#649 stat chapter type added
  src/types/ICourse.ts
Labels: enhancement

#650 transaction removed from detached processes
  src/utils/version-helpers.ts
Labels: enhancement

#653 Improvements from Develop
  package-lock.json
  src/components/DeleteButton.tsx
  src/components/Editor.tsx
  src/components/SignUpProfessionalInfo.tsx
  src/components/chats/BubbleChart.tsx
  src/components/chats/PointsBarChart.tsx
  src/components/instructors/Drawers/StudentFilters.tsx
  src/components/instructors/setting/NewCourse.tsx
  src/components/map/CommunityLeaderboard/CommunityLeaderboard.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UserSettingsProfessionalInfo.tsx
  src/global.css
  src/pages/api/checkTag.ts
  src/pages/dashboard.tsx
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/instructors/settings.tsx
  src/pages/instructors/students.tsx
  src/styles/app.css
  src/types/ICourse.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#656 Develop from Improvements
  src/pages/dashboard.tsx
Labels: bug

#657 stopped Typesense to indexing deleted nodes
  typesenseIndexer/index.ts
Labels: bug

#673 Improvements from Develop
  src/components/chats/BubbleChart.tsx
  src/components/chats/PointsBarChart.tsx
  src/components/chats/TrendPlot.tsx
  src/components/instructors/HeaderNavbar.tsx
  src/components/instructors/HeaderNavbarMovil.tsx
  src/components/instructors/dashboard/GeneralPlotStats.tsx
  src/components/map/ClustersList.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/Sidebar/Sidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/components/map/Sidebar/TrendsPlotRow.tsx
  src/components/map/Sidebar/UseInfoTrends.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/components/map/UserStatusIcon.tsx
  src/components/map/UserStatusSettings.tsx
  src/context/AuthContext.tsx
  src/global.css
  src/hooks/useThemeChange.ts
  src/hooks/useWorkerQueue.tsx
  src/knowledgeTypes.ts
  src/lib/firestoreClient/auth.ts
  src/lib/reducers/auth.ts
  src/lib/utils/Map.utils.ts
  src/lib/utils/charts.utils.ts
  src/lib/utils/dagre.util.ts
  src/lib/utils/routes.ts
  src/pages/dashboard.tsx
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/node/[title]/[id].tsx
  src/pages/notebook.tsx
  src/workers/MapWorker.ts
  typesenseIndexer/index.ts
Labels: bug, enhancement

#697 Controlled re-rendering of Sidebars
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/CitationsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
Labels: bug, enhancement

#703 simulate bakend response in frontend to reduce change in frontend
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/hooks/useWorkerQueue.tsx
  src/lib/utils/Map.utils.ts
  src/nodeBookTypes.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/rateVersion.ts
  src/pages/notebook.tsx
  src/utils/helpers.ts
  src/utils/index.tsx
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#706 Improvements from Develop
  src/components/chats/BubbleChart.tsx
  src/components/instructors/dashboard/GeneralPlotStats.tsx
  src/components/instructors/setting/Proposal.tsx
  src/components/instructors/setting/Vote.tsx
  src/components/layouts/StudentsLayout.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/components/map/ProposalsList/ProposalsList.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/CitationsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/hooks/useWorkerQueue.tsx
  src/lib/utils/Map.utils.ts
  src/nodeBookTypes.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/rateVersion.ts
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/instructors/settings.tsx
  src/pages/instructors/students.tsx
  src/pages/notebook.tsx
  src/utils/helpers.ts
  src/utils/index.tsx
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#705 Semester settings api fixed
  src/pages/api/instructor/students/[semesterId]/setting.ts
Labels: bug, enhancement

#707 Semester settings api fixed
  src/pages/api/instructor/students/[semesterId]/setting.ts
Labels: bug, enhancement

#709 Fix the issue with two scrollbars on the students' list page for instructors.
  src/components/instructors/Drawers/StudentFilters.tsx
  src/pages/instructors/students.tsx
Labels: bug

#717 student sign up usernode for semester and bugfix for uname document
  src/pages/api/instructor/students/[semesterId]/signup.ts
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  testUtils/mockData/students.stats.data.ts
Labels: bug, enhancement

#741 SearcherSidebar clean on next search
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
Labels: bug, enhancement

#742 fixed issues in the students Page for instructors
  src/components/CSVBtn.tsx
  src/pages/instructors/students.tsx
Labels: bug

#745 remove redrawing on graph on usernode snapshots
  src/pages/notebook.tsx
Labels: bug

#746 Improvements from Develop
  src/components/CSVBtn.tsx
  src/components/map/Sidebar/NotificationsList.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/CitationsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/global.css
  src/lib/reducers/nodeBook.ts
  src/nodeBookTypes.ts
  src/pages/instructors/students.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#749 improvements from develop
  src/pages/notebook.tsx
Labels: bug, enhancement

#751 create notification num document if not present
  src/pages/notebook.tsx
Labels: bug

#752 improvement from develop
  src/pages/notebook.tsx
Labels: bug

#758 simulte backend response in frontend to reduce change in frontend
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug

#759 simulte backend response in frontend to reduce change in frontend
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#761 Fix/760 notification number error
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/global.css
  src/pages/notebook.tsx
Labels: bug, enhancement

#762 merge to main
  src/components/instructors/setting/Proposal.tsx
  src/components/instructors/setting/Vote.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/global.css
  src/pages/notebook.tsx
Labels: bug, enhancement

#769 Feature/767 clean code in frontend
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/components/map/Proposals.tsx
  src/components/map/Sidebar/Bookmarks.tsx
  src/components/map/Sidebar/BookmarksButton.tsx
  src/components/map/Sidebar/Citations.tsx
  src/components/map/Sidebar/Notifications.tsx
  src/components/map/Sidebar/NotificationsButton.tsx
  src/components/map/Sidebar/PendingProposalsButton.tsx
  src/components/map/Sidebar/SearchList.css
  src/components/map/Sidebar/Sidebar.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/components/map/Sidebar/SidebarWrapper.tsx
  src/components/map/Sidebar/UserInfo.tsx
  src/components/map/Sidebar/UserSettings.tsx
  src/pages/dashboard.tsx
  src/pages/notebook.tsx
Labels: bug

#789 handle ambiguous children, parents in Propose node improvement
  src/pages/api/proposeNodeImprovement.ts
Labels: bug

#794 Improvements from Develop
  src/components/instructors/HeaderNavbar.tsx
  src/components/instructors/HeaderNavbarMovil.tsx
  src/components/instructors/SemesterFilter.tsx
  src/components/instructors/skeletons/UserProfileSkeleton.tsx
  src/components/layouts/InstructorsLayout.tsx
  src/components/layouts/StudentsLayout.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/components/map/Proposals.tsx
  src/components/map/Sidebar/Bookmarks.tsx
  src/components/map/Sidebar/BookmarksButton.tsx
  src/components/map/Sidebar/BookmarksList.tsx
  src/components/map/Sidebar/Citations.tsx
  src/components/map/Sidebar/Notifications.tsx
  src/components/map/Sidebar/NotificationsButton.tsx
  src/components/map/Sidebar/NotificationsList.tsx
  src/components/map/Sidebar/PendingProposalsButton.tsx
  src/components/map/Sidebar/SearchList.css
  src/components/map/Sidebar/Sidebar.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/components/map/Sidebar/SidebarWrapper.tsx
  src/components/map/Sidebar/UserInfo.tsx
  src/components/map/Sidebar/UserSettings.tsx
  src/hooks/useWorkerQueue.tsx
  src/pages/api/proposeNodeImprovement.ts
  src/pages/dashboard.tsx
  src/pages/notebook.tsx
  src/styles/app.css
Labels: bug, enhancement

#798 Feature/739 dont change selected node when are proposing a node
  package-lock.json
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#799 change to new image
  public/lightModeLibraryBackground.jpg
Labels: enhancement

#800 Feature/763 fix error data in students and duplicated semesters
  src/components/layouts/InstructorsLayout.tsx
  src/components/layouts/StudentsLayout.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/instructors/students.tsx
Labels: bug

#804 merge develop to main
  package-lock.json
  public/lightModeLibraryBackground.jpg
  src/components/instructors/setting/Proposal.tsx
  src/components/layouts/InstructorsLayout.tsx
  src/components/layouts/StudentsLayout.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/instructors/students.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#810 Sankey Chart for instructor dashboard
  package-lock.json
  package.json
  src/components/chats/SankeyChart.tsx
  src/lib/sankey.ts
  src/pages/instructors/dashboard.tsx
Labels: bug, enhancement

#813 node footer simlation fixed on edit or new child proposal
  src/components/map/NodeFooter.tsx
Labels: bug, enhancement

#815 Sankey chart label colors according selected theme
  src/components/chats/SankeyChart.tsx
Labels: bug

#814 Improvements from Develop
  package-lock.json
  package.json
  src/components/chats/SankeyChart.tsx
  src/components/instructors/SemesterFilter.tsx
  src/components/instructors/dashboard/GeneralPlotStats.tsx
  src/components/instructors/setting/Chapter.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/CitationsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/global.css
  src/instructorsTypes.ts
  src/lib/sankey.ts
  src/lib/utils/charts.utils.ts
  src/nodeBookTypes.ts
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/instructors/students.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#818 names instead of unames
  src/components/chats/SankeyChart.tsx
  src/pages/instructors/dashboard.tsx
Labels: enhancement

#819 enhancements in sankey chart
  src/components/chats/SankeyChart.tsx
  src/pages/instructors/dashboard.tsx
Labels: enhancement

#833 add message when there aren't proposals in proposal sidebar
  src/components/map/ProposalsList/ProposalsList.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/pages/notebook.tsx
Labels: bug

#835 proposal sidebar list reload on every time you click on pencil icon
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
Labels: bug

#839 Disable voting buttons until response arrives for vote
  src/components/map/MetaButton.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/global.css
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#841 scroll To Node fixed when nodes opened from search sidebar
  src/pages/notebook.tsx
Labels: bug

#855 add frontend guidelines
  FrontendGuidelines.md
  README.md
Labels: documentation

#856 Fix/853 proposals are not changing while click in tabs
  src/components/map/ContainedButton.tsx
  src/components/map/ProposalsList/ProposalsList.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
Labels: bug

#862 merge develop to main
  FrontendGuidelines.md
  README.md
  src/components/chats/BoxChart.tsx
  src/components/chats/HorizontalBarsChart.tsx
  src/components/chats/TrendPlot.tsx
  src/components/layouts/InstructorsLayout.tsx
  src/components/layouts/StudentsLayout.tsx
  src/components/map/ContainedButton.tsx
  src/components/map/MetaButton.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/ProposalsList/ProposalsList.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/global.css
  src/nodeBookTypes.ts
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/notebook.tsx
  src/styles/app.css
Labels: bug, enhancement

#868 fix remove proposal
  src/pages/notebook.tsx
Labels: bug

#869 merge develop to main
  src/pages/notebook.tsx
Labels: bug

#877 merge develop to main
  src/components/TagsSearcher.tsx
  src/components/chats/PointsBarChart.tsx
  src/components/chats/SankeyChart.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/hooks/useComponentSize.tsx
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/notebook.tsx
  src/styles/app.css
Labels: bug, enhancement

#878 Leaderboard liveliness and community switching fixed
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/global.css
  src/pages/notebook.tsx
Labels: bug, enhancement

#879 Leaderboard Liveliness and Community Switcher
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/global.css
  src/pages/notebook.tsx
Labels: bug

#880 25hr logic implemented directly on endpoints
  __tests__/pages/api/proposeChildNode.test.ts
  __tests__/pages/api/proposeNodeImprovement.test.ts
  __tests__/pages/api/rateVersion.test.ts
  __tests__/pages/api/signup.test.ts
  __tests__/pages/api/wrongNode.test.ts
  __tests__/utils/upDownVoteNode/upDownVoteNode.test.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/rateVersion.ts
  src/pages/api/signup.ts
  src/types/IInstitution.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
  testUtils/fakers/institution.ts
  testUtils/fakers/user.ts
Labels: enhancement

#881 signup error if email doesn't match with institute
  __tests__/pages/api/signup.test.ts
  src/pages/api/signup.ts
Labels: enhancement

#883 knowledge testing memory increased
  .github/workflows/knowledgeTesting.yml
Labels: enhancement

#894 searchNodesInNotebook api bug fix
  src/pages/api/searchNodesInNotebook.ts
Labels: bug

#896 Improvements from Develop
  src/components/TagsSearcher.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/NewChildProposal.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/ProposalsList/ProposalsList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/components/map/UserStatusIcon.tsx
  src/global.css
  src/hooks/useTagsTreeView.ts
  src/lib/theme/brandingTheme.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#912 set isNew to false, on userNodes snapshot for new child
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug

#917 reference title change bugfix in changeNodeTitle
  src/utils/version-helpers.ts
Labels: bug

#918 reference title change bugfix in changeNodeTitle
  src/utils/version-helpers.ts
Labels: bug

#910 Fix/uniform input and bottons searcher sidebar
  src/components/map/NodeFooter.tsx
  src/components/map/RecentNodesList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/components/map/ValidatedInput.tsx
  src/global.css
  src/lib/theme/brandingTheme.ts
  src/styles/app.css
Labels: bug, enhancement

#926 node content prefetch using serverside props
  src/lib/utils/utils.ts
  src/pages/node/[title]/[id].tsx
Labels: bug

#925 Fix/improve node css bugs
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/LinkingWords/ReferenceLabelInput.tsx
  src/components/map/MetaButton.tsx
  src/components/map/NodeFooter.tsx
  src/global.css
Labels: bug, enhancement

#929 change serverside props to static props with blocking fallback
  src/pages/node/[title]/[id].tsx
Labels: bug

#932 Sitemap generator node alias logic updated
  sitemap-generator/index.js
  src/lib/utils/utils.ts
Labels: enhancement

#933 contributior to array in typesense indexing
  src/utils/version-helpers.ts
Labels: bug

#934 Improvements from Develop
  sitemap-generator/index.js
  src/components/instructors/setting/Proposal.tsx
  src/components/instructors/setting/Vote.tsx
  src/components/map/CommunityLeaderboard/CommunityLeaderboard.tsx
  src/components/map/ContainedButton.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/LinkingWords/ReferenceLabelInput.tsx
  src/components/map/MetaButton.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/RecentNodesList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/components/map/ValidatedInput.tsx
  src/global.css
  src/lib/theme/brandingTheme.ts
  src/lib/utils/utils.ts
  src/pages/node/[title]/[id].tsx
  src/pages/notebook.tsx
  src/styles/ComLeaderboard.css
  src/styles/app.css
  src/utils/version-helpers.ts
Labels: bug, enhancement
