Repository ImanYZ/1Cademy-Public, pull requests merged in 2022-12, with the labels that each got.

#935 Tmp/toolbar issues original
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#944 Selection of Reference when proposing new node
  src/components/map/LinkingWords/LinkingWords.tsx
Labels: bug

#946 Selection of Reference when proposing new node
  src/components/map/LinkingWords/LinkingWords.tsx
Labels: bug

#945 Improvements from Develop
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/lib/theme/brandingTheme.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#952 reputation signal on correct, wrong action
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/knowledgeTypes.ts
  src/lib/firestoreServer/admin.ts
  src/lib/utils/Map.utils.ts
  src/pages/notebook.tsx
  src/utils/helpers.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: enhancement

#960 semester setting added new flags
  __tests__/pages/api/instructor/students/[semesterId]/setting.test.ts
  src/pages/api/instructor/course/create.ts
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/types/ICourse.ts
  testUtils/fakers/course.ts
Labels: bug, enhancement

#959 Improvements from Develop
  __tests__/pages/api/addProposal.test.ts
  __tests__/pages/api/changeDefaultTag/deTagNode.test.ts
  __tests__/pages/api/instructor/students/[semesterId]/setting.test.ts
  __tests__/pages/api/instructor/students/[semesterId]/signup.test.ts
  __tests__/pages/api/proposeNodeImprovement.test.ts
  __tests__/utils/fetchGoogleGeoLocation.test.ts
  src/components/instructors/setting/Proposal.tsx
  src/components/instructors/setting/Vote.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/knowledgeTypes.ts
  src/lib/firestoreServer/admin.ts
  src/lib/utils/Map.utils.ts
  src/pages/api/instructor/course/create.ts
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/pages/instructors/settings.tsx
  src/pages/notebook.tsx
  src/types/ICourse.ts
  src/utils/helpers.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
  testUtils/fakers/course.ts
Labels: bug, enhancement

#964 Searcher load more bug fixed
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
Labels: bug

#965 Actiontracking setup from required actions
  __tests__/pages/api/correctNode.test.ts
  __tests__/pages/api/proposeChildNode.test.ts
  __tests__/pages/api/proposeNodeImprovement.test.ts
  __tests__/pages/api/rateVersion.test.ts
  __tests__/pages/api/wrongNode.test.ts
  __tests__/utils/upDownVoteNode/upDownVoteNode.test.ts
  __tests__/utils/version-helpers/versionCreateUpdate.test.ts
  src/components/map/LivelinessBar.tsx
  src/pages/api/proposeChildNode.ts
  src/pages/notebook.tsx
  src/types/IActionTrack.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: enhancement

#972 liveliness bar implementation
  __tests__/pages/api/proposeChildNode.test.ts
  __tests__/pages/api/proposeNodeImprovement.test.ts
  src/components/map/Liveliness/ActionBubble.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/LivelinessBar.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/knowledgeTypes.ts
  src/lib/utils/Map.utils.ts
  src/pages/_document.tsx
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/rateVersion.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/notebook.tsx
  src/types/IActionTrack.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: enhancement

#974 Liveliness bar changed from horizontal to vertical
  src/components/map/Liveliness/LivelinessBar.tsx
  src/pages/notebook.tsx
Labels: enhancement

#975 Notebook liveliness bar
  src/components/map/Liveliness/ActionBubble.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/pages/notebook.tsx
Labels: enhancement

#977 Add Video feature on node
  src/components/map/Node.tsx
  src/components/map/Node/NodeVideo.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/lib/utils/utils.ts
  src/pages/notebook.tsx
Labels: enhancement

#979 Livelinessbar snapshot updates based on interval
  src/components/map/Liveliness/LivelinessBar.tsx
Labels: enhancement

#980 Livelinessbar clear on snapshot reset
  src/components/map/Liveliness/LivelinessBar.tsx
Labels: enhancement

#981 First load initializer
  src/components/map/Liveliness/LivelinessBar.tsx
Labels: enhancement

#982 Improvements from Develop
  __tests__/pages/api/correctNode.test.ts
  __tests__/pages/api/proposeChildNode.test.ts
  __tests__/pages/api/proposeNodeImprovement.test.ts
  __tests__/pages/api/rateVersion.test.ts
  __tests__/pages/api/wrongNode.test.ts
  __tests__/utils/upDownVoteNode/upDownVoteNode.test.ts
  __tests__/utils/version-helpers/versionCreateUpdate.test.ts
  src/components/instructors/setting/NewCourse.tsx
  src/components/instructors/setting/Proposal.tsx
  src/components/map/Liveliness/ActionBubble.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Node.tsx
  src/components/map/Node/NodeVideo.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/ProposalsList/ProposalItem/ProposalItem.tsx
  src/components/map/Sidebar/BookmarksList.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/CitationsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/knowledgeTypes.ts
  src/lib/utils/Map.utils.ts
  src/lib/utils/utils.ts
  src/pages/_document.tsx
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/rateVersion.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/instructors/settings.tsx
  src/pages/notebook.tsx
  src/types/IActionTrack.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#985 uniform colors for liveliness sidebar and node collapse icon on sidebar
  src/components/map/Liveliness/LivelinessBar.tsx
  src/pages/notebook.tsx
Labels: bug

#986 Uniform color of liveliness sidebar with other sidebar colors
  src/components/Markdown/MarkdownRender.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/CitationsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/pages/notebook.tsx
Labels: bug

#997 liveliness bar chooseUname feature added, update image in action track on image change
  src/components/map/Liveliness/LivelinessBar.tsx
  src/lib/utils/Map.utils.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/rateVersion.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/notebook.tsx
  src/types/IActionTrack.ts
  src/utils/upDownVoteNode.ts
  src/utils/updateUserImageEverywhere.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#998 Liveliness online/offline status
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1001 notebook online status should not change for current user
  src/pages/notebook.tsx
Labels: bug

#1003 User presense with uuid based session ids
  cloud-functions/functions/index.js
  src/context/ThemeContext.tsx
Labels: enhancement

#1006 User presense with uuid based session ids
  cloud-functions/functions/index.js
  src/context/ThemeContext.tsx
Labels: enhancement

#1010 node focus view
  src/components/HtmlTooltip.tsx
  src/components/NodeItemFull.tsx
  src/components/ShareButtons.tsx
  src/components/map/FocusedNotebook/FocusedLinkedNodes.tsx
  src/components/map/FocusedNotebook/FocusedNodeContributors.tsx
  src/components/map/FocusedNotebook/FocusedNodeSkeleton.tsx
  src/components/map/FocusedNotebook/FocusedNotebook.tsx
  src/components/map/FocusedNotebook/FocusedReferencesList.tsx
  src/components/map/FocusedNotebook/FocusedTagsList.tsx
  src/components/map/FocusedNotebook/HeadlessLeaderboardChip.tsx
  src/components/map/Node.tsx
  src/components/map/NodeHeader.tsx
  src/components/map/NodesList.tsx
  src/pages/node/[title]/[id].tsx
  src/pages/notebook.tsx
Labels: enhancement

#1011 Focused view for Notebook
  src/components/HtmlTooltip.tsx
  src/components/NodeItemFull.tsx
  src/components/ShareButtons.tsx
  src/components/map/FocusedNotebook/FocusedLinkedNodes.tsx
  src/components/map/FocusedNotebook/FocusedNodeContributors.tsx
  src/components/map/FocusedNotebook/FocusedNodeSkeleton.tsx
  src/components/map/FocusedNotebook/FocusedNotebook.tsx
  src/components/map/FocusedNotebook/FocusedReferencesList.tsx
  src/components/map/FocusedNotebook/FocusedTagsList.tsx
  src/components/map/FocusedNotebook/HeadlessLeaderboardChip.tsx
  src/components/map/Node.tsx
  src/components/map/NodeHeader.tsx
  src/components/map/NodesList.tsx
  src/pages/node/[title]/[id].tsx
  src/pages/notebook.tsx
Labels: enhancement

#1016 Restore node to final state
  src/components/map/ProposalsList/ProposalsList.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1015 tooltip refactor for image upload
  src/components/map/NodeFooter.tsx
  src/components/map/NodeHeader.tsx
Labels: enhancement

#1017 Improvements from Develop
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodeHeader.tsx
  src/components/map/ProposalsList/ProposalsList.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1020 Liveliness bar profile image without skew
  src/components/map/Liveliness/LivelinessBar.tsx
Labels: enhancement

#1021 Liveliness bar profile image without skew
  src/components/map/Liveliness/LivelinessBar.tsx
Labels: enhancement

#1024 node type change feature in improvement api
  __tests__/pages/api/contributorsAutocomplete.test.ts
  __tests__/pages/api/searchNodesInNotebook.test.ts
  __tests__/utils/version-helpers/addTagCommunityAndTagsOfTags.test.ts
  __tests__/utils/version-helpers/getVersion.test.ts
  src/components/map/Node.tsx
  src/components/map/Node/NodeTypeSelector.tsx
  src/components/map/NodeFooter.tsx
  src/nodeBookTypes.ts
  src/pages/api/deleteVersion.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/rateVersion.ts
  src/pages/notebook.tsx
  src/types/INode.ts
  src/types/INodeVersion.ts
  src/utils/getTypedCollections.ts
  src/utils/helpers.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
  testUtils/mockCollections/conceptVersions.data.ts
Labels: enhancement

#1026 light mode for liveliness bar
  src/components/map/Liveliness/LivelinessBar.tsx
Labels: enhancement

#1031 node type change to question and add choices
  src/pages/api/proposeNodeImprovement.ts
Labels: enhancement

#1033 show node type on notebook when selecting proposal
  src/pages/notebook.tsx
Labels: bug

#1035 node type title in dropdown
  src/components/map/Node/NodeTypeSelector.tsx
Labels: enhancement

#1038 enlarge video icon in node editable
  src/components/map/NodeFooter.tsx
Labels: bug

#1043 show user info sidebar when click on avatar in liveliness bar
  src/components/map/Liveliness/LivelinessBar.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1044 Improvement from Develop
  __tests__/pages/api/contributorsAutocomplete.test.ts
  __tests__/pages/api/searchNodesInNotebook.test.ts
  __tests__/utils/version-helpers/addTagCommunityAndTagsOfTags.test.ts
  __tests__/utils/version-helpers/getVersion.test.ts
  src/components/Editor.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Node.tsx
  src/components/map/Node/NodeTypeSelector.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodeHeader.tsx
  src/components/map/ProposalsList/ProposalItem/ProposalItem.tsx
  src/components/map/ProposalsList/ProposalsList.tsx
  src/components/map/QuestionChoices.tsx
  src/components/map/Sidebar/BookmarksList.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/nodeBookTypes.ts
  src/pages/api/deleteVersion.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/rateVersion.ts
  src/pages/notebook.tsx
  src/types/INode.ts
  src/types/INodeVersion.ts
  src/utils/getTypedCollections.ts
  src/utils/helpers.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
  testUtils/mockCollections/conceptVersions.data.ts
Labels: enhancement

#1045 open pending proposal state on node when opened from sidebar
  src/components/map/Sidebar/PendingProposalList.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/lib/reducers/nodeBook.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1046 Improved pending proposal list
  src/components/map/Sidebar/PendingProposalList.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/lib/reducers/nodeBook.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1053 Receiver points in actionTrack document for NoteVote
  src/types/IActionTrack.ts
  src/utils/upDownVoteNode.ts
Labels: enhancement

#1061 notebook hide correct/wrong and other control on unaccepted proposal
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/pages/notebook.tsx
Labels: bug

#1062 Home migration in progress
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/pages/notebook.tsx
  src/types/IActionTrack.ts
  src/utils/upDownVoteNode.ts
Labels: bug

#1067 Reputation and Interaction
  src/lib/utils/Map.utils.ts
  src/pages/notebook.tsx
Labels: enhancement

#1071 font size fixed for changedAt in node
  src/components/map/NodeFooter.tsx
Labels: enhancement

#1073 calculated User info reputation for current community
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
Labels: enhancement

#1078 Improvements from Develop
  src/components/LeaderboardChip.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/Sidebar/ProfileAvatar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/pages/notebook.tsx
Labels: bug

#1084 rateVersion use nodeType of version collection
  src/pages/api/rateVersion.ts
Labels: bug

#1085 rateVersion use nodeType of version collection
  src/pages/api/rateVersion.ts
Labels: bug

#1088 rateVersion transaction error fixed and deps updated for rateProposal callback
  src/pages/notebook.tsx
  src/utils/version-helpers.ts
Labels: bug

#1089 rateVersion transaction error fixed and deps updated for rateProposal callback
  src/pages/notebook.tsx
  src/utils/version-helpers.ts
Labels: bug

#1091 Hide negative reputation from Reputation Livebar
  src/components/map/Liveliness/ReputationBar.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1092 Hide negative reputation from Reputation Livebar
  src/components/map/Liveliness/ReputationBar.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1093 hide negative reputation from live sidebar
  src/components/map/Liveliness/ReputationBar.tsx
Labels: enhancement

#1094 hide negative reputation from live sidebar
  src/components/map/Liveliness/ReputationBar.tsx
Labels: enhancement
