Repository ImanYZ/1Cademy-Public, pull requests merged in 2022-10, with the labels that each got.

#145 Api tests improvements
  __tests__/utils/upDownVoteNode/upDownVoteNode.test.ts
  testUtils/typesenseMocks/index.ts
Labels: bug, test

#162 Optimized Critical APIs
  __tests__/pages/api/proposeNodeImprovement.test.ts
  __tests__/utils/upDownVoteNode/upDownVoteNode.test.ts
  src/utils/helpers.ts
  src/utils/upDownVoteNode.ts
Labels: enhancement

#163 npm ci trigger updated
  Dockerfile
Labels: enhancement

#172 Node link shorten
  src/lib/utils/utils.ts
  src/pages/n/[nodeId].tsx
Labels: enhancement

#173 node url shorten
  .gitignore
  pages/n/[nodeId].tsx
Labels: enhancement

#184 Improved api/uploadImage endpoint
  src/pages/api/uploadImage.ts
Labels: bug

#186 try/catch in api/uploadImage
  src/pages/api/uploadImage.ts
Labels: bug

#247 Fixed margin issue in node tags, childrens, parents and references
  src/components/map/LinkingWords/LinkingButton.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/MetaButton.tsx
Labels: enhancement

#294 test improved for /api/wrongNode.ts
  __tests__/pages/api/wrongNode.test.ts
Labels: test

#295 when i open the app for the first time if i don’t have any nodes opened before ;it keeps loading
  src/pages/dashboard.tsx
Labels: bug

#319 Sidebar reputations list fixed
  src/components/map/Sidebar/Sidebar.tsx
Labels: bug

#330 Sidebar node search fixed
  src/components/map/Sidebar/SearchList.tsx
Labels: bug

#329 fix issues in the Next Button SignUp Page
  src/components/SignUpBasicInfo.tsx
  src/pages/signup.tsx
Labels: bug

#338 disable the loader image in the first load temporarily
  src/pages/dashboard.tsx
Labels: bug

#346 Fixed community tag not update issues in user settings
  src/components/map/Sidebar/UserSettings.tsx
  src/knowledgeTypes.ts
  src/lib/reducers/auth.ts
Labels: bug

#360 Fixed city and state dropdown rendering on selected default country
  src/components/SignUpPersonalInfo.tsx
Labels: bug

#362 Added mark color same as 1cademy.com in node footer for upVote
  src/components/map/NodeFooter.tsx
Labels: enhancement

#373 pending proposals, bookmarks, and notifications numbers should update accordingly.
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/pages/dashboard.tsx
Labels: bug

#378 fix the dependencies for the useEffects updating notifications and pending list numbers
  src/pages/dashboard.tsx
Labels: bug

#326 Added user presence functionality on cloud and frontend
  cloud-functions/.firebaserc.example
  cloud-functions/.gitignore
  cloud-functions/database.rules.json
  cloud-functions/firebase.json
  cloud-functions/firestore.indexes.json
  cloud-functions/firestore.rules
  cloud-functions/functions/.gitignore
  cloud-functions/functions/index.js
  cloud-functions/functions/package-lock.json
  cloud-functions/functions/package.json
  cloud-functions/package-lock.json
  cloud-functions/package.json
  cloud-functions/remoteconfig.template.json
  cloud-functions/storage.rules
  src/context/ThemeContext.tsx
Labels: enhancement

#382 Birthdate doesn't exist for some users in production
  src/lib/firestoreClient/auth.ts
Labels: bug

#385 Typesense readme.md updated
  typesenseIndexer/README.md
Labels: documentation

#397 user presence cloud function
  cloud-functions/functions/index.js
Labels: bug

#403 Editor state fixed to cleanup on next edit
  pages/_app.tsx
  pages/n/[nodeId].tsx
  pages/proposal/[id].tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/pages/dashboard.tsx
Labels: bug

#404 Fixed bug with proposing to change the parent or children on a node
  pages/_app.tsx
  pages/n/[nodeId].tsx
  pages/proposal/[id].tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/pages/dashboard.tsx
Labels: bug

#419 monthly, weekly reputations doesn't showup in sidebar after submitting proposal
  __tests__/pages/api/proposeNodeImprovement.test.ts
  src/components/map/Sidebar/UsersStatusList.tsx
  src/pages/api/proposeNodeImprovement.ts
Labels: bug

#420 Improve from develop to main
  __tests__/pages/api/proposeNodeImprovement.test.ts
  components/NodeItemFullEditor.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/pages/api/proposeNodeImprovement.ts
  src/pages/dashboard.tsx
Labels: bug

#424 Improvements from develop to main
  src/components/map/Sidebar/UsersStatusList.tsx
  src/pages/api/proposeNodeImprovement.ts
  src/pages/dashboard.tsx
Labels: bug

#427 proposeNodeImprovement api bug fix
  src/utils/version-helpers.ts
Labels: bug

#426 The trashcan button for deleting the pending proposals does not show up! #402
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
Labels: bug
