Repository ImanYZ/1Cademy-Public, pull requests merged in 2023-06, with the labels that each got.

#2136 Assistant response cache
  src/knowledgeTypes.ts
  src/lib/typesense/typesense.config.ts
  src/pages/api/assistant.ts
  src/types/IAssistant.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2139 Fix/dashboards
  src/components/PointsType.tsx
  src/components/chats/BubbleChart.tsx
  src/components/chats/PointsBarChart.tsx
  src/components/chats/SankeyChart.tsx
  src/components/map/dashboard/Dashboard.tsx
  src/lib/utils/charts.utils.ts
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/types/ICourse.ts
Labels: bug

#2140 merge to main
  src/components/PointsType.tsx
  src/components/chats/BubbleChart.tsx
  src/components/chats/PointsBarChart.tsx
  src/components/chats/SankeyChart.tsx
  src/components/map/dashboard/Dashboard.tsx
  src/lib/utils/charts.utils.ts
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/types/ICourse.ts
Labels: bug

#2141 create conversation for cache assistant response
  src/pages/api/assistant.ts
Labels: enhancement

#2142 create conversation for cache assistant response
  src/pages/api/assistant.ts
Labels: enhancement

#2143 fix daily streak
  __tests__/client/utils/userStatus.utils.test.ts
  src/lib/utils/userStatus.utils.ts
Labels: bug

#2144 Merge to main
  __tests__/client/utils/userStatus.utils.test.ts
  src/lib/utils/userStatus.utils.ts
Labels: bug

#2148 change thumbnails on demo section
  public/home/demos/practice-preview.png
  public/home/demos/practice-tool-demo.jpg
  public/home/demos/practice-tool-demo.png
  public/home/demos/question-answering-demo.jpg
  public/home/demos/question-answering-demo.png
  src/components/home/sections/Demos.tsx
Labels: enhancement

#2150 Feauture/fix leaderboards by the new no user image
  src/client/firestore/user.firestore.ts
  src/components/OptimizedAvatar2.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/lib/utils/constants.ts
Labels: bug

#2152 Unit detection fixed for Assistant Nodes
  src/pages/api/assistant.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2153 Improvements from develop
  public/home/demos/practice-preview.png
  public/home/demos/practice-tool-demo.jpg
  public/home/demos/practice-tool-demo.png
  public/home/demos/question-answering-demo.jpg
  public/home/demos/question-answering-demo.png
  src/client/firestore/user.firestore.ts
  src/components/OptimizedAvatar2.tsx
  src/components/home/sections/Demos.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/lib/utils/constants.ts
  src/pages/api/assistant.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2155 update title
  src/components/home/sections/Hero.tsx
Labels: enhancement

#2158 Unit no detection fixed in Assistant
  src/utils/assistant-helpers.ts
Labels: enhancement

#2160 Liveliness bar snapshot re-initialization fixed
  src/components/map/Liveliness/LivelinessBar.tsx
Labels: enhancement

#2161 Fix/dashboards
  __tests__/client/utils/chart.utils.test.ts
  __tests__/client/utils/dashboard.test.ts
  src/client/firestore/semesters.firestore.ts
  src/client/firestore/user.firestore.ts
  src/components/OptimizedAvatar2.tsx
  src/components/chats/BoxChart.tsx
  src/components/chats/BubbleChart.tsx
  src/components/chats/Legend.tsx
  src/components/chats/StackBarChart.tsx
  src/components/chats/TrendPlot.tsx
  src/components/instructors/dashboard/GeneralPlotStats.tsx
  src/components/instructors/skeletons/BoxPlotStatsSkeleton.tsx
  src/components/map/dashboard/Dashboard.tsx
  src/components/map/dashboard/DashboardStudents.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/UserStatus.tsx
  src/instructorsTypes.ts
  src/lib/utils/charts.utils.ts
  src/lib/utils/dashboard.utils.ts
  src/lib/utils/routes.ts
  src/pages/dashboards/[semester]/[uname].tsx
  src/pages/instructors/chapters.json
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/instructors/settings_old.tsx
  src/pages/instructors/students.tsx
  src/pages/instructors/tmp.tsx
  src/styles/app.css
  src/types.ts
  src/types/ICourse.ts
Labels: bug, enhancement

#2163 Merge to main
  __tests__/client/utils/chart.utils.test.ts
  __tests__/client/utils/dashboard.test.ts
  src/client/firestore/semesters.firestore.ts
  src/client/firestore/user.firestore.ts
  src/components/Header/AppHeader.tsx
  src/components/Header/MenuHeader.tsx
  src/components/OptimizedAvatar2.tsx
  src/components/chats/BoxChart.tsx
  src/components/chats/BubbleChart.tsx
  src/components/chats/Legend.tsx
  src/components/chats/StackBarChart.tsx
  src/components/chats/TrendPlot.tsx
  src/components/community/JoinUs.tsx
  src/components/home/HomeWrapper.tsx
  src/components/home/SectionsItems.tsx
  src/components/home/components/SectionWrapper.tsx
  src/components/home/sections/Hero.tsx
  src/components/instructors/dashboard/GeneralPlotStats.tsx
  src/components/instructors/skeletons/BoxPlotStatsSkeleton.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/dashboard/Dashboard.tsx
  src/components/map/dashboard/DashboardStudents.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/UserStatus.tsx
  src/instructorsTypes.ts
  src/lib/utils/charts.utils.ts
  src/lib/utils/dashboard.utils.ts
  src/lib/utils/routes.ts
  src/pages/dashboards/[semester]/[uname].tsx
  src/pages/home.tsx
  src/pages/instructors/chapters.json
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/instructors/settings_old.tsx
  src/pages/instructors/students.tsx
  src/pages/instructors/tmp.tsx
  src/styles/app.css
  src/types.ts
  src/types/ICourse.ts
  src/utils/assistant-helpers.ts
Labels: bug, enhancement

#2168 fix scroll to node on search sidebar
  src/hooks/useWorkerQueue.tsx
  src/pages/notebook.tsx
Labels: bug

#2170 Fix/hide descendants
  src/lib/utils/nodesSyncronization.utils.ts
  src/pages/notebook.tsx
Labels: enhancement

#2171 merge to main
  src/components/instructors/SemesterSelect.tsx
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/Dashobard/DashboradToolbar.tsx
  src/components/map/Node.tsx
  src/components/map/RecentNodesList.tsx
  src/components/map/Sidebar/SearchList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/TimeFilter.tsx
  src/components/map/Toolbox.tsx
  src/components/map/UserStatusIcon2.tsx
  src/global.css
  src/hooks/useWorkerQueue.tsx
  src/lib/utils/develop.util.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/lib/utils/tutorials/nodeTutorialSteps.tsx
  src/lib/utils/tutorials/notificationsTutorialSteps.tsx
  src/lib/utils/tutorials/reconcilingProposalsTutorialSteps.tsx
  src/lib/utils/tutorials/searcherTutorialSteps.tsx
  src/pages/notebook.tsx
  src/pages/notebooks/[title]/[id].tsx
Labels: bug, enhancement

#2173 Feature/preload nodes from visible nodes
  package-lock.json
  public/service-worker.js
  src/client/firestore/userNodes.firestore.ts
  src/components/NodeItemFullEditor.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/lib/utils/nodesSyncronization.utils.ts
  src/lib/utils/utils.ts
  src/nodeBookTypes.ts
  src/pages/_app.tsx
  src/pages/notebook.tsx
  src/pages/notebooks/[title]/[id].tsx
  src/workers/MapWorker.ts
Labels: enhancement

#2177 enable fullscreen on node video
  package-lock.json
  package.json
  src/components/map/Node/NodeVideo.tsx
Labels: bug, enhancement

#2178 merge to main
  package-lock.json
  package.json
  public/service-worker.js
  src/client/firestore/userNodes.firestore.ts
  src/components/NodeItemFullEditor.tsx
  src/components/map/Node/NodeVideo.tsx
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/lib/utils/nodesSyncronization.utils.ts
  src/lib/utils/utils.ts
  src/nodeBookTypes.ts
  src/pages/_app.tsx
  src/pages/notebook.tsx
  src/pages/notebooks/[title]/[id].tsx
  src/workers/MapWorker.ts
Labels: bug, enhancement

#2180 Feature/update voice assistant animations
  __tests__/client/utils/userStatus.utils.test.ts
  public/rive-voice-assistant/assistant-state-machine.old.rev
  public/rive-voice-assistant/assistant-state-machine.old.riv
  public/rive-voice-assistant/assistant-state-machine.riv
  src/client/firestore/semesterStudentVoteStats.firestores.ts
  src/components/map/Assistant.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/Leaderboard.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/components/practiceTool/UserStatus.tsx
  src/lib/utils/speechRecognitions.utils.ts
  src/lib/utils/userStatus.utils.ts
  src/pages/notebook.tsx
  src/utils/helpers.ts
Labels: bug, enhancement

#2187 Feature/update leaderboard tutorial and merge toolbox tutorials
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/hooks/userHover.ts
  src/lib/utils/tutorials/leaderBoardTutorialSteps.tsx
  src/lib/utils/tutorials/toolbooxTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2188 merge to main
  public/home/demos/introduction-instructor-ad-student-dashboard.png
  src/components/home/sections/Demos.tsx
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/hooks/userHover.ts
  src/lib/utils/tutorials/leaderBoardTutorialSteps.tsx
  src/lib/utils/tutorials/toolbooxTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2190 Feature/notebooks tutorial
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/notebooksTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#2191 merge to main
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/notebooksTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#2193 implement cloud function to create log from action tracks
  cloud-functions/functions/index.js
Labels: enhancement

#2200 fix scrollToNode function
  src/pages/notebook.tsx
Labels: bug

#2201 Merge to main
  cloud-functions/functions/index.js
  src/pages/notebook.tsx
Labels: bug, enhancement

#2209 Content Assistant APIs and Notebook event listeners
  cloud-functions/firebase.json
  cloud-functions/functions/.gitignore
  cloud-functions/functions/index.js
  cloud-functions/functions/package-lock.json
  cloud-functions/functions/package.json
  cloud-functions/functions/src/index.ts
  cloud-functions/functions/src/types/IActionTrack.ts
  cloud-functions/functions/src/types/IUser.ts
  cloud-functions/functions/tsconfig.json
  src/components/map/Node.tsx
  src/nodeBookTypes.ts
  src/pages/api/assistant/combineContent.ts
  src/pages/api/assistant/createNotebook.ts
  src/pages/api/assistant/getFlashcards.ts
  src/pages/api/assistant/getNotebooks.ts
  src/pages/api/assistant/proposeFlashcard.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/notebook.tsx
  src/types/IAssistant.ts
  src/types/IAssitantConversation.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2210 Content Assistant APIs and event listeners
  cloud-functions/firebase.json
  cloud-functions/functions/.gitignore
  cloud-functions/functions/index.js
  cloud-functions/functions/package-lock.json
  cloud-functions/functions/package.json
  cloud-functions/functions/src/index.ts
  cloud-functions/functions/src/types/IActionTrack.ts
  cloud-functions/functions/src/types/IUser.ts
  cloud-functions/functions/tsconfig.json
  src/components/map/Node.tsx
  src/nodeBookTypes.ts
  src/pages/api/assistant/combineContent.ts
  src/pages/api/assistant/createNotebook.ts
  src/pages/api/assistant/getFlashcards.ts
  src/pages/api/assistant/getNotebooks.ts
  src/pages/api/assistant/proposeFlashcard.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/notebook.tsx
  src/types/IAssistant.ts
  src/types/IAssitantConversation.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2222 Fix/improve positive reinforcement animation
  public/rive/positive-reinforcement.riv
  src/components/assistant/mechanismItems.ts
  src/components/home/sections/Mechanism.tsx
Labels: bug

#2223 Fix/node header option when is simulated
  src/components/map/Node.tsx
  src/pages/notebook.tsx
Labels: bug
