Repository ImanYZ/1Cademy-Public, pull requests merged in 2023-08, with the labels that each got.

#2392 add link on research comunities section on home page
  src/components/home/SectionsItems.tsx
  src/components/home/components/SectionWrapper.tsx
Labels: enhancement

#2393 fix build errors
  src/components/home/components/SectionWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/pages/notebook.tsx
Labels: bug

#2394 merge to main
  src/components/home/SectionsItems.tsx
  src/components/home/components/SectionWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/pages/notebook.tsx
Labels: enhancement

#2399 change name of file from newid to newFirestoreId
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/lib/utils/newFirestoreId.ts
  src/pages/notebook.tsx
Labels: bug

#2398 merge to main
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/lib/utils/newFirestoreId.ts
  src/pages/notebook.tsx
Labels: bug

#2404 Added 404 go back link
  src/pages/404.tsx
Labels: enhancement

#2405 Added 404 go back link
  src/pages/404.tsx
Labels: enhancement

#2408 merge to main
  .vscode/settings.json
  src/client/firestore/questions.firestore.ts
  src/components/CSVBtn.tsx
  src/components/OptimizedAvatar2.tsx
  src/components/map/BasicNodeFooter.tsx
  src/components/map/Buttons/Buttons.tsx
  src/components/map/Dashobard/DashboradToolbar.tsx
  src/components/map/dashboard/Assignments.tsx
  src/components/map/dashboard/DashboardStudents.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/map/dashboard/QuestionItem.tsx
  src/components/map/dashboard/RubricItem.tsx
  src/components/map/dashboard/RubricsEditor.tsx
  src/components/map/dashboard/UserAnswers.tsx
  src/hooks/useUploadImage.tsx
  src/pages/api/assignment/generateRubrics.ts
  src/pages/api/assignment/tryRubric.ts
  src/pages/notebook.tsx
  src/types.ts
  src/utils/assignments-helpers.ts
Labels: enhancement

#2417 merge to main
  package-lock.json
  package.json
  src/client/firestore/answer.firestore.ts
  src/client/firestore/temporalUsers.firestore.ts
  src/client/firestore/user.firestore.ts
  src/components/instructors/SemesterSelect.tsx
  src/components/map/Dashobard/DashboradToolbar.tsx
  src/components/map/dashboard/Assignments.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/map/dashboard/RubricItem.tsx
  src/components/map/dashboard/RubricsEditor.tsx
  src/components/map/dashboard/UserAnswers.tsx
  src/pages/api/assignment/tryRubric.ts
Labels: bug

#2421 userInteractions wrapped in setUserInteractions to get latest values
  src/components/map/Liveliness/LivelinessBar.tsx
Labels: bug

#2424 save on state the image height to not detect change and increase in 1…
  src/components/map/Node.tsx
  src/global.css
Labels: bug

#2422 userInteractions wrapped in setUserInteractions to get latest values
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Node.tsx
  src/global.css
Labels: enhancement

#2431 Fix/some issues
  cloud-functions/datasets/edited_universities.json
  cloud-functions/functions/src/admin.ts
  cloud-functions/functions/src/assignNodeContributorsInstitutionsStats.ts
  cloud-functions/functions/src/index.ts
  cloud-functions/functions/src/updateInstitutions.ts
  scheduler/.dockerignore
  scheduler/Dockerfile
  scheduler/cloudbuild.yaml
  scheduler/docker-compose.yml
  scheduler/getTypedCollections.js
  scheduler/index.js
  scheduler/package-lock.json
  scheduler/package.json
  scheduler/readme.md
  src/components/home/HomeWrapper.tsx
  src/components/home/components/SectionWrapper.tsx
  src/components/map/Dashobard/DashboradToolbar.tsx
  src/components/map/Sidebar/ProfileAvatar.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#2435 Merge to main
  src/components/chats/StackBarChart.tsx
  src/components/map/Dashobard/DashboradToolbar.tsx
  src/components/map/dashboard/Assignments.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/map/dashboard/RubricItem.tsx
  src/hooks/useUploadImage.tsx
Labels: bug, enhancement

#2436 fix padding on user answers
  src/components/map/dashboard/UserAnswers.tsx
Labels: bug

#2437 merge to main
  src/components/map/dashboard/UserAnswers.tsx
Labels: bug

#2439 Feature/improve autograding
  next.config.js
  src/client/firestore/answer.firestore.ts
  src/client/firestore/questions.firestore.ts
  src/components/map/dashboard/Assignments.tsx
  src/components/map/dashboard/RubricsEditor.tsx
  src/components/map/dashboard/UserAnswers.tsx
Labels: enhancement

#2440 merge to main
  next.config.js
  src/client/firestore/answer.firestore.ts
  src/client/firestore/questions.firestore.ts
  src/components/map/dashboard/Assignments.tsx
  src/components/map/dashboard/RubricsEditor.tsx
  src/components/map/dashboard/UserAnswers.tsx
Labels: enhancement

#2444 fix id sended to the enpoint to check if is aproved automatically
  src/pages/api/instructor/course/checkInstantApprovalForProposal.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/proposeParentNode.ts
  src/pages/notebook.tsx
  src/utils/course-helpers.ts
Labels: bug

#2445 merge to main
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/pages/api/instructor/course/checkInstantApprovalForProposal.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/proposeParentNode.ts
  src/pages/notebook.tsx
  src/types.ts
  src/utils/course-helpers.ts
Labels: bug

#2448 Fix/simulation on create new node
  src/components/map/ProposalsList/ProposalsList.tsx
  src/lib/utils/develop.util.ts
  src/pages/notebook.tsx
  src/utils/version-helpers.ts
Labels: bug

#2449 merge to main
  src/components/map/ProposalsList/ProposalsList.tsx
  src/lib/utils/develop.util.ts
  src/pages/notebook.tsx
  src/utils/version-helpers.ts
Labels: bug

#2453 Feature/allow to remove proposals to the owners
  src/components/map/ProposalsList/ProposalsList.tsx
Labels: enhancement

#2455 merge to main
  __tests__/client/components/map/AbsoluteLivelinessBar.test.tsx
  __tests__/client/components/map/RelativeLivelinessBar.test.tsx
  __tests__/client/components/map/liveliness.utils.test.tsx
  cloud-functions/functions/src/index.ts
  cloud-functions/functions/src/types/IUser.ts
  package.json
  src/client/firestore/actionTracks.firestore.ts
  src/components/map/Liveliness/ActionBubble.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/RelativeLivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/Liveliness/UserBubble.tsx
  src/components/map/Liveliness/liveliness.utils.ts
  src/components/map/ProposalsList/ProposalsList.tsx
  src/knowledgeTypes.ts
  src/lib/utils/Map.utils.ts
  src/lib/utils/develop.util.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/api/proposeParentNode.ts
  src/pages/api/rateVersion.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/api/signup.ts
  src/pages/notebook.tsx
  src/types.ts
  src/types/IActionTrack.ts
  src/utils/upDownVoteNode.ts
Labels: bug, enhancement

#2460 Canonical Alt added for Search Console
  src/components/NodeHead.tsx
  src/pages/home.tsx
Labels: enhancement
