Repository ImanYZ/1Cademy-Public, pull requests merged in 2023-05, with the labels that each got.

#1922 signup test fixed
  __tests__/pages/api/instructor/students/[semesterId]/signup.test.ts
  __tests__/pages/api/signup.test.ts
  src/pages/api/signup.ts
Labels: bug

#1923 update long term learning section
  public/rive/long-term-learning.riv
  src/components/home/sections/Mechanism.tsx
Labels: enhancement

#1929 add reset button on animations on homePage
  src/components/assistant/Mechanism.tsx
  src/components/home/components/temporals/RiveComponentExtended.tsx
  src/components/home/sections/Mechanism.tsx
  src/components/home/sections/Systems.tsx
Labels: enhancement

#1931 Fix/animation homepage
  public/rive/evaluating.riv
  public/rive/improving.riv
  public/rive/long-term-learning.riv
Labels: bug

#1935 add contextialized Q&A
  public/rive/contextualized-q-a.riv
  src/components/home/sections/Mechanism.tsx
Labels: enhancement

#1945 update paul resnik picture
  public/home/about/02.jpeg
  public/home/about/02.old.jpg
  src/components/home/components/AboutSwitcher.tsx
Labels: enhancement

#1952 Fix/practice tool question
  src/components/CustomCircularProgress.tsx
  src/components/chats/BoxChart.tsx
  src/components/chats/PointsBarChart.tsx
  src/components/instructors/SemesterSelect.tsx
  src/components/map/Dashobard/DashboradToolbar.tsx
  src/components/map/dashboard/Dashboard.tsx
  src/components/practiceTool/CourseDetail.tsx
  src/components/practiceTool/Leaderboard.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/components/practiceTool/UserStatus.tsx
  src/lib/utils/date.utils.ts
Labels: bug

#1962 update animations for contextualized Q&A and long term learning
  public/rive/contextualized-q-a.riv
  public/rive/long-term-learning.riv
Labels: bug, enhancement

#1966 Assistant Prompts improved
  src/utils/assistant-helpers.ts
Labels: enhancement

#1967 Assistant prompts improved
  src/utils/assistant-helpers.ts
Labels: enhancement

#1971 assistant backend improvements
  __tests__/utils/assistant-helpers/parseJSONMarkdownObjectsFromResponse.test.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#1972 complete to add percentage loader in profile picture
  src/components/map/PercentageLoader.tsx
  src/components/map/Sidebar/ProfileAvatar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/global.css
Labels: enhancement

#1973 merge to main
  __tests__/utils/assistant-helpers/parseJSONMarkdownObjectsFromResponse.test.ts
  src/components/map/PercentageLoader.tsx
  src/components/map/Sidebar/ProfileAvatar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/global.css
  src/utils/assistant-helpers.ts
Labels: enhancement

#1974 Create semester notebook on students enroll
  __tests__/pages/api/instructor/students/[semesterId]/signup.test.ts
  __tests__/pages/api/signup.test.ts
  src/pages/api/instructor/students/[semesterId]/signup.ts
  src/pages/api/signup.ts
  src/utils/course-helpers.ts
Labels: enhancement

#1977 add validation to course and chat notebooks
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/pages/notebook.tsx
  src/types.ts
Labels: enhancement

#1984 Start practice bug fixed
  src/components/practiceTool/Leaderboard.tsx
Labels: enhancement

#1987 Feature/update animations on home page
  public/rive/asistant_evaluating.riv
  public/rive/contextualized-q-a.riv
  public/rive/improving.riv
  public/rive/linking.riv
  public/rive/long-term-learning.riv
  public/rive/summarizing.riv
Labels: enhancement

#1988 Next question node selection and reverse bfs bug in practice tool
  src/pages/api/checkAnswer.ts
  src/utils/course-helpers.ts
Labels: bug

#1990 createPractice helper questionNode list replacement fixed
  src/utils/version-helpers.ts
Labels: enhancement

#1996 fixed Node url having 2 slashes after domain
  src/lib/utils/utils.ts
Labels: bug

#1998 Student stats in practice endpoint
  __tests__/pages/api/checkAnswer.test.ts
  __tests__/pages/api/practice.test.ts
  __tests__/utils/version-helpers/createPractice.test.ts
  src/pages/api/practice.ts
  src/utils/course-helpers.ts
  src/utils/version-helpers.ts
Labels: enhancement

#2000 Implemented ID Token event handler using iframe
  src/pages/_app.tsx
  src/pages/iframe.tsx
  src/pages/notebook.tsx
  src/types/IAssistant.ts
Labels: enhancement

#1999 Feature/implement demo section on 1cademy
  public/home/1cademy-youtube-channel.jpg
  public/home/demos/practice-tool-demo.jpg
  public/home/demos/question-answering-demo.jpg
  src/components/AppHeaderSearchBar2.tsx
  src/components/Header/AppHeader.tsx
  src/components/OptimizedAvatar2.tsx
  src/components/home/components/AboutSwitcher.tsx
  src/components/home/components/SectionWrapper.tsx
  src/components/home/sections/About.tsx
  src/components/home/sections/Demos.tsx
  src/components/home/sections/Papers.tsx
  src/lib/utils/string.utils.ts
  src/pages/assistant.tsx
  src/pages/home.tsx
Labels: enhancement

#2001 merge to main
  __tests__/pages/api/checkAnswer.test.ts
  __tests__/pages/api/practice.test.ts
  __tests__/utils/version-helpers/createPractice.test.ts
  public/home/1cademy-youtube-channel.jpg
  public/home/demos/practice-tool-demo.jpg
  public/home/demos/question-answering-demo.jpg
  public/rive/asistant_evaluating.riv
  public/rive/contextualized-q-a.riv
  public/rive/improving.riv
  public/rive/linking.riv
  public/rive/long-term-learning.riv
  public/rive/summarizing.riv
  src/components/AppHeaderSearchBar2.tsx
  src/components/Header/AppHeader.tsx
  src/components/OptimizedAvatar2.tsx
  src/components/home/components/AboutSwitcher.tsx
  src/components/home/components/SectionWrapper.tsx
  src/components/home/sections/About.tsx
  src/components/home/sections/Demos.tsx
  src/components/home/sections/Papers.tsx
  src/components/practiceTool/Leaderboard.tsx
  src/lib/utils/string.utils.ts
  src/lib/utils/utils.ts
  src/pages/_app.tsx
  src/pages/api/checkAnswer.ts
  src/pages/api/practice.ts
  src/pages/assistant.tsx
  src/pages/home.tsx
  src/pages/iframe.tsx
  src/pages/notebook.tsx
  src/types/IAssistant.ts
  src/utils/course-helpers.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#2003 Feature/fix notebook features
  src/components/map/Node.tsx
  src/pages/notebook.tsx
Labels: bug

#2004 Merge to main
  src/components/map/Node.tsx
  src/pages/notebook.tsx
Labels: bug

#2010 Feature/improvements notebook and homepage
  src/components/home/sections/Demos.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
Labels: bug, enhancement

#2011 merge to main
  src/components/home/sections/Demos.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
Labels: bug, enhancement

#2013 Fix/change tag on toolbar
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/lib/firestoreClient/notebooks.serverless.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2014 merge to main
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/lib/firestoreClient/notebooks.serverless.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2019 Task/2006 voice only
  package-lock.json
  package.json
  public/assistant.svg
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/instructorsTypes.ts
  src/lib/utils/assistant.utils.ts
  src/lib/utils/constants.ts
  src/lib/utils/speechRecognitions.utils.ts
  src/lib/utils/string.utils.ts
  src/nodeBookTypes.ts
  src/pages/api/practice.ts
  src/pages/notebook.tsx
  src/types/IAssistant.ts
  src/utils/helpers.ts
  src/utils/node.utils.ts
  src/workers/NarrateWorker.ts
Labels: enhancement

#2020 Task/2006 voice only
  public/rive-voice-assistant/happy.riv
  public/rive-voice-assistant/idle.riv
  public/rive-voice-assistant/listening.riv
  public/rive-voice-assistant/sad.riv
  public/rive-voice-assistant/snoring.riv
  public/rive-voice-assistant/talking.riv
  src/components/map/Assistant.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/hooks/usePrevious.ts
  src/lib/utils/constants.ts
  src/lib/utils/speechRecognitions.utils.ts
  src/lib/utils/string.utils.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
  src/utils/helpers.ts
Labels: enhancement

#2025 Tmp/2006 voice only v3
  src/components/map/Assistant.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/lib/utils/constants.ts
  src/lib/utils/narrator.utils.ts
  src/lib/utils/speechRecognitions.utils.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
  src/utils/helpers.ts
Labels: bug, enhancement

#2026 add selected question narrated
  src/components/map/Assistant.tsx
Labels: bug, enhancement

#2033 add scroll to node when open a node from practice tool
  src/components/practiceTool/PracticeQuestion.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#2034 Improvements from develop
  src/components/practiceTool/PracticeQuestion.tsx
  src/pages/notebook.tsx
Labels: enhancement

#2039 Notebook listener to store extension id for assistant dev
  src/lib/utils/assistant.utils.ts
  src/pages/_app.tsx
  src/pages/iframe.tsx
  src/types/IAssistant.ts
Labels: enhancement

#2042 Feature/leadeboard is not ordered based on their practice points
  src/components/practiceTool/Leaderboard.tsx
Labels: bug

#2041 dynamic Extension id for dev version of Assistant extension
  src/components/practiceTool/Leaderboard.tsx
  src/lib/utils/assistant.utils.ts
  src/pages/_app.tsx
  src/pages/iframe.tsx
  src/types/IAssistant.ts
Labels: enhancement

#2044 Updated Assistant Prompts to have individual complitions
  src/pages/api/assistant.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2045 Assistant api enhancements
  src/pages/api/assistant.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2046 Feature/display a way to stop voice interactions
  src/components/map/Assistant.tsx
  src/pages/notebook.tsx
Labels: bug

#2049 Feature/2048 change letters to numbers
  src/components/map/Assistant.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/lib/utils/assistant.utils.ts
  src/lib/utils/constants.ts
  src/lib/utils/speechRecognitions.utils.ts
  src/utils/helpers.ts
Labels: bug, enhancement

#2050 merge to main
  src/components/map/Assistant.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/lib/utils/assistant.utils.ts
  src/lib/utils/constants.ts
  src/lib/utils/speechRecognitions.utils.ts
  src/pages/notebook.tsx
  src/utils/helpers.ts
Labels: bug, enhancement

#2052 add animations by state machine
  public/rive-voice-assistant/assistant-state-machine.rev
  public/rive-voice-assistant/assistant-state-machine.riv
  src/components/map/Assistant.tsx
Labels: enhancement

#2055 fix scroll to node on practice voice only
  src/components/map/Assistant.tsx
  src/pages/notebook.tsx
Labels: bug

#2057 continue practicing when click on assistant icon
  src/components/map/Assistant.tsx
Labels: enhancement

#2058 merge to main
  src/components/map/Assistant.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#2060 Feature/2059 fix practice tool bugs
  src/components/CustomCircularProgress.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/utils/helpers.ts
Labels: bug, enhancement

#2063 add video on demo section + move demo section into systems
  public/home/demos/practice-preview.png
  src/components/home/sections/Demos.tsx
  src/components/home/sections/Systems.tsx
  src/pages/home.tsx
Labels: enhancement

#2065 Fix/assistant recognition
  src/components/map/Assistant.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/lib/utils/constants.ts
  src/lib/utils/speechRecognitions.utils.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2067 Bard node query api endpoint updated
  src/pages/api/assistant.ts
  src/pages/api/bardQuery.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2068 Implementation of Bard query for nodes
  src/pages/api/assistant.ts
  src/pages/api/bardQuery.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2071 Merge to main
  src/components/map/Assistant.tsx
Labels: bug

#2076 Task/2035 assistant helpers
  src/components/map/dashboard/Dashboard.tsx
  src/lib/utils/charts.utils.ts
  src/pages/api/assistant/createConversation.ts
Labels: bug

#2077 Merge to main
  src/components/map/dashboard/Dashboard.tsx
  src/lib/utils/charts.utils.ts
  src/pages/api/assistant/createConversation.ts
Labels: bug, enhancement

#2081 force detect voices
  src/utils/helpers.ts
Labels: bug

#2082 Merge to main
  src/utils/helpers.ts
Labels: bug

#2092 Feature/improve clickeable assistant
  src/components/map/Assistant.tsx
Labels: enhancement

#2097 Fix/2093 practice tool visual bugs
  __tests__/client/utils/userStatus.utils.test.ts
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/components/map/UserStatusIcon.tsx
  src/components/map/UserStatusIcon2.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/Leaderboard.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/components/practiceTool/UserStatus.tsx
  src/lib/utils/constants.ts
  src/lib/utils/userStatus.utils.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2083 display tooltip on bar-chart on instructor dasboard
  src/lib/utils/charts.utils.ts
Labels: bug

#2099 Fix/hydratation error
  src/components/home/components/AboutSwitcher.tsx
Labels: bug

#2105 different Tag id selection based on user
  src/pages/api/assistant.ts
  src/pages/api/bardQuery.ts
Labels: enhancement

#2110 Feature/improve practice tool
  src/components/CustomCircularProgress.tsx
  src/components/map/Assistant.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
Labels: enhancement

#2115 Feature/add logs in practice tool
  src/client/firestore/nodes.firestore.ts
  src/client/firestore/semesterStudentVoteStat.firestores.ts
  src/client/firestore/semesters.firestore.ts
  src/components/map/Assistant.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/Leaderboard.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/components/practiceTool/UserStatus.tsx
  src/pages/notebook.tsx
Labels: enhancement

#2120 enable sankey chart for instructors + fix typos on code
  .vscode/settings.json
  src/components/chats/PointsBarChart.tsx
  src/components/chats/SankeyChart.tsx
  src/components/instructors/skeletons/SankeyChartSkeleton.tsx
  src/components/map/Dashobard/DashboradToolbar.tsx
  src/components/map/dashboard/Dashboard.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
Labels: bug

#2122 Fix/visual bugs on toolbar
  src/components/PointsType.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/components/map/SidebarButtons.tsx
  src/components/map/UserStatusIcon2.tsx
  src/components/map/UserStatusSettings2.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/components/practiceTool/UserStatus.tsx
  src/hooks/userHover.ts
  src/lib/utils/date.utils.ts
Labels: bug

#2123 merge to main
  .vscode/settings.json
  src/client/firestore/nodes.firestore.ts
  src/client/firestore/practiceToolLog.firestore.ts
  src/client/firestore/semesterStudentVoteStat.firestores.ts
  src/client/firestore/semesters.firestore.ts
  src/components/PointsType.tsx
  src/components/chats/PointsBarChart.tsx
  src/components/chats/SankeyChart.tsx
  src/components/instructors/skeletons/SankeyChartSkeleton.tsx
  src/components/map/Assistant.tsx
  src/components/map/Dashobard/DashboradToolbar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/components/map/SidebarButtons.tsx
  src/components/map/UserStatusIcon2.tsx
  src/components/map/UserStatusSettings2.tsx
  src/components/map/dashboard/Dashboard.tsx
  src/components/map/dashboard/DashboardWrapper.tsx
  src/components/practiceTool/Leaderboard.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/practiceTool/PracticeTool.tsx
  src/components/practiceTool/UserStatus.tsx
  src/hooks/userHover.ts
  src/lib/utils/date.utils.ts
  src/pages/instructors/dashboard.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#2125 Merge to main
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/SidebarButtons.tsx
  src/hooks/userHover.ts
Labels: bug

#2126 Fix/visual bugs on toolbar
  src/components/map/CustomBudge.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/SidebarButtons.tsx
  src/components/practiceTool/UserStatus.tsx
Labels: bug

#2131 Assistant APIs for new prototype
  src/pages/api/assistant/combineContent.ts
  src/pages/api/assistant/createChat.ts
  src/pages/api/assistant/getFlashcards.ts
  src/pages/api/assistant/getNotebooks.ts
  src/pages/api/assistant/getReferenceNodes.ts
  src/pages/api/assistant/getTopic.ts
  src/pages/api/bardQuery.ts
  src/pages/api/viewNode/[nodeId].ts
  src/pages/api/viewNode/openNodes.ts
  src/types/IAssitantConversation.ts
  src/utils/assistant-helpers.ts
Labels: enhancement

#2133 typo fixed for sankey chart
  src/types/ICourse.ts
  src/utils/course-helpers.ts
Labels: enhancement
