Repository ImanYZ/1Cademy-Public, pull requests merged in 2023-02, with the labels that each got.

#1306 Fix/scroll in home pages
  public/assistant/7-signals-how-close-dark.svg
  public/assistant/7-signals-how-close.svg
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
  src/components/home/views/HowItWorks.tsx
  src/components/home/views/Values.tsx
  src/components/home/views/Which.tsx
  src/pages/assistant.tsx
  src/pages/index.tsx
Labels: bug

#1310 merge to main
  public/assistant/7-signals-how-close-dark.svg
  public/assistant/7-signals-how-close.svg
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
  src/components/home/views/HowItWorks.tsx
  src/components/home/views/Values.tsx
  src/components/home/views/Which.tsx
  src/pages/assistant.tsx
  src/pages/index.tsx
Labels: bug

#1313 Feature/update images in home pages
  public/assistant/10-uses-scientifically-proven-dark.svg
  public/assistant/10-uses-scientifically-proven.svg
  public/assistant/11-leverages-methods-dark.svg
  public/assistant/11-leverages-methods.svg
  public/assistant/8-motivates-through.svg
  public/assistant/9-allows-you-to-easily-modify.svg
  src/components/Markdown/MarkdownRender.tsx
  src/components/assistant/HowItWorks.tsx
  src/components/home/views/HowItWorks.tsx
  src/components/home/views/Values.tsx
  src/components/home/views/Which.tsx
  src/components/home/views/WhoWeAre.tsx
  src/pages/assistant.tsx
  src/pages/home.tsx
  src/pages/index.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#1317 auto tagging higher communities on new or improvement proposal
  __tests__/pages/api/proposeChildNode.tags.test.ts
  __tests__/pages/api/proposeNodeImprovement.tags.test.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/utils/version-helpers.ts
Labels: enhancement

#1319 Updated cloudbuild substitutions to pass extension id on build time
  Dockerfile
  cloudbuild.dev.yaml
  cloudbuild.yaml
Labels: enhancement

#1328 Feature/refactor home page from 1cademy.com
  public/1Cademy-head.svg
  public/home/1Cademy.png
  public/home/about/Iman_YeckehZaare.jpg
  public/home/about/Iman_YeckehZaare.old.jpg
  public/home/about/Paul_Resnick.jpg
  public/home/about/logo-google-cloud.png
  public/home/about/logo-honor.jpg
  public/home/about/logo-school-of-information.jpg
  public/home/communities/01-ux-research-psychology-of-learning.jpg
  public/home/communities/02-clinicalpsychology.jpg
  public/home/communities/03-health-psychology.jpg
  public/home/communities/04-disability-studies.jpg
  public/home/communities/05-social-psychology.jpg
  public/home/communities/06-natural-language-processing.jpg
  public/home/communities/07-ux-research-communities.jpg
  public/home/communities/08-liaisonlibrarians.jpg
  public/rive/logo.riv
  src/components/AppFooter3.tsx
  src/components/AppHeader2.tsx
  src/components/AppHeaderSearchBar2.tsx
  src/components/home/SectionsItems.tsx
  src/components/home/components/UniversitiesMap/UniversitiesMap.tsx
  src/components/home/sections/About.tsx
  src/components/home/sections/Benefits.tsx
  src/components/home/sections/Join.tsx
  src/components/home/sections/Magnitude.tsx
  src/components/home/sections/Mechanism.tsx
  src/components/home/sections/Papers.tsx
  src/components/home/sections/Systems.tsx
  src/components/home/sections/Topics.tsx
  src/components/home/views/Hero.tsx
  src/components/home/views/HowItWorks.tsx
  src/components/home/views/valuesItems.ts
  src/components/home/views/whichValues.ts
  src/lib/utils/RE.ts
  src/lib/utils/routes.ts
  src/lib/utils/string.utils.ts
  src/pages/home.tsx
  src/pages/home2.tsx
Labels: enhancement

#1344 Installed python3 in builder
  Dockerfile
Labels: enhancement

#1347 Fixed duplicate tagging bug in generateTagsOfTagsWithNodes
  src/utils/version-helpers.ts
Labels: enhancement

#1348 Improvements from develop
  Dockerfile
  src/utils/version-helpers.ts
Labels: enhancement

#1356 node improvement bug fix on removing tag/tags
  src/utils/version-helpers.ts
Labels: enhancement

#1357 Deferred Queues for Worker
  src/hooks/useWorkerQueue.tsx
Labels: enhancement

#1358 Improvements from Develop
  src/hooks/useWorkerQueue.tsx
  src/utils/version-helpers.ts
Labels: enhancement

#1360 decreased queue deferer time
  __tests__/utils/version-helpers/generateTagsData.test.ts
  src/hooks/useWorkerQueue.tsx
Labels: enhancement

#1367 Fixed memory bug in node voting
  src/utils/upDownVoteNode.ts
Labels: enhancement

#1368 Improvements from develop
  __tests__/pages/api/proposeNodeImprovement.test.ts
  __tests__/utils/version-helpers/generateTagsData.test.ts
  src/components/map/FocusedNotebook/FocusedNotebook.tsx
  src/components/map/Node.tsx
  src/hooks/useWorkerQueue.tsx
  src/lib/utils/utils.ts
  src/pages/api/proposeNodeImprovement.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: enhancement

#1375 merge to main
  public/home/about/01.jpg
  public/home/about/02.jpg
  public/home/about/03.jpg
  public/home/about/1200x-1 1.jpg
  src/components/home/components/AoutSwitcher.tsx
  src/components/home/components/Photo.tsx
  src/components/home/sections/About.tsx
  src/components/home/sections/Papers.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1376 Feature/improve home page 2
  public/home/about/1200x-1 1.jpg
  public/home/about/Iman_YeckehZaare.jpg
  public/home/about/Iman_YeckehZaare.old.jpg
  public/home/about/Paul_Resnick.jpg
  public/home/papers/runestone-academy.png
  src/components/Header/AppHeader.tsx
  src/components/Header/SubMenu.tsx
  src/components/assistant/Benefits.tsx
  src/components/home/HomeWrapper.tsx
  src/components/home/components/AboutSwitcher.tsx
  src/components/home/components/SectionItemSwitcher.tsx
  src/components/home/sections/About.tsx
  src/components/home/sections/Benefits.tsx
  src/components/home/sections/Hero.tsx
  src/components/home/sections/Join.tsx
  src/components/home/sections/Magnitude.tsx
  src/components/home/sections/Systems.tsx
  src/pages/assistant.tsx
  src/pages/home.tsx
Labels: enhancement

#1405 auto tag ancestor tags to new Child node
  src/pages/api/proposeChildNode.ts
Labels: enhancement

#1406 Improvements from develop
  src/components/SignUpProfessionalInfo.tsx
  src/components/map/FocusedNotebook/FocusedNotebook.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/Node.tsx
  src/components/map/NodeHeader.tsx
  src/components/modals/CookiePolicy.tsx
  src/components/modals/GDPRPolicy.tsx
  src/components/modals/PrivacyPolicy.tsx
  src/components/modals/TermsOfUse.tsx
  src/pages/api/proposeChildNode.ts
  src/pages/notebook.tsx
Labels: enhancement

#1417 transaction lock logic updated in up/down vote api
  __tests__/utils/reputations/updateReputation.test.ts
  __tests__/utils/reputations/updateReputationIncrement.test.ts
  __tests__/utils/upDownVoteNode/upDownVoteNode.test.ts
  src/pages/api/proposeChildNode.ts
  src/utils/reputations.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: enhancement

#1418 Improvements from develop
  __tests__/utils/reputations/updateReputation.test.ts
  __tests__/utils/reputations/updateReputationIncrement.test.ts
  __tests__/utils/upDownVoteNode/upDownVoteNode.test.ts
  public/focus.svg
  src/components/SignUpProfessionalInfo.tsx
  src/components/home/sections/Papers.tsx
  src/pages/api/proposeChildNode.ts
  src/pages/notebook.tsx
  src/pages/signup.tsx
  src/utils/reputations.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: bug, enhancement

#1421 course create api updated to add tags of tags in new nodes
  src/pages/api/instructor/course/create.ts
Labels: enhancement

#1423 fix new course button in first click
  src/components/layouts/InstructorsLayout.tsx
  src/lib/utils/routes.ts
Labels: bug

#1424 height simulation implemented
  src/global.css
  src/pages/notebook.tsx
Labels: enhancement

#1425 height simulation implemented
  src/components/layouts/InstructorsLayout.tsx
  src/global.css
  src/lib/utils/routes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1439 notebook ref implemented on notebook, node and node list
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/hooks/useWorkerQueue.tsx
  src/lib/reducers/nodeBook.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1446 Feature/add interactive tutorial
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/LinkingWords/LinkingButton.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/tutorial/ProgressBar.tsx
  src/components/tutorial/ProgressBarMenu.tsx
  src/hooks/useInteractiveTutorial2.tsx
  src/hooks/useWorkerQueue.tsx
  src/lib/reducers/nodeTutorial.tsx
  src/lib/utils/Map.utils.ts
  src/lib/utils/interactiveTutorialNodes.tsx
  src/lib/utils/interactoveTutorialNodeTypes.tsx
  src/nodeBookTypes.ts
  src/pages/home.tsx
  src/pages/notebook.tsx
  src/styles/app.css
Labels: enhancement

#1449 Feature/add interactive tutorial
  src/components/map/LinkingWords/LinkingButton.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/UserStatusIcon.tsx
  src/hooks/useInteractiveTutorial2.tsx
  src/lib/reducers/nodeTutorial.tsx
  src/lib/utils/interactiveTutorialNodes.tsx
  src/pages/notebook.tsx
  src/styles/app.css
  src/workers/MapWorker.ts
Labels: bug

#1454 course backend fixes and node selection fixed
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/pages/notebook.tsx
  src/utils/course-helpers.ts
Labels: enhancement

#1455 Question Proposal detection on Course backend
  src/pages/api/proposeChildNode.ts
  src/utils/course-helpers.ts
Labels: enhancement

#1457 Feature/refactorize tutorial steps
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/RecentNodesList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/ValidatedInput.tsx
  src/components/tutorial/ProgressBarMenu.tsx
  src/hooks/useInteractiveTutorial2.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/reducers/nodeTutorial.tsx
  src/lib/reducers/nodeTutorial2.tsx
  src/lib/reducers/searcherTutorial.tsx
  src/lib/utils/interactiveTutorialNodes.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#1458 improved implementation of Tags of tags
  __tests__/pages/api/signup.test.ts
  src/pages/api/instructor/students/[semesterId]/signup.ts
  src/pages/api/signup.ts
  src/utils/version-helpers.ts
Labels: enhancement

#1459 improved course setting api
  src/pages/api/instructor/students/[semesterId]/setting.ts
  src/utils/version-helpers.ts
Labels: enhancement

#1466 Feature/improve node tutorial
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/lib/reducers/searcherTutorial.tsx
  src/pages/notebook.tsx
Labels: bug
