Repository ImanYZ/1Cademy-Public, pull requests merged in 2023-07, with the labels that each got.

#2238 Feature/1843 implement new sidebars while linking in propose evaluate mode
  src/client/firestore/userNodes.firestore.ts
  src/components/map/Buttons/Buttons.tsx
  src/components/map/RecentNodesList.tsx
  src/components/map/Sidebar/SearchInput.tsx
  src/components/map/Sidebar/SidebarNodeLink.tsx
  src/components/map/Sidebar/SidebarV2/ParentsChildrenSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ReferencesSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper2.tsx
  src/components/map/Sidebar/SidebarV2/TagsSidebar.tsx
  src/components/map/dashboard/DashboardStudents.tsx
  src/hooks/useTagsTreeView.ts
  src/knowledgeTypes.ts
  src/lib/utils/Map.utils.ts
  src/lib/utils/constants.ts
  src/lib/utils/develop.util.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/lib/utils/tutorials/nodeConceptTutorialStep.tsx
  src/pages/api/searchNodes.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/notebook.tsx
  src/types.ts
  src/utils/dates.ts
Labels: bug, enhancement

#2239 Feature/update cloud function to create action tracks 24h
  cloud-functions/functions/src/index.ts
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
Labels: bug, enhancement

#2240 merge to main
  cloud-functions/functions/src/index.ts
  src/client/firestore/userNodes.firestore.ts
  src/components/map/BasicNode.tsx
  src/components/map/Buttons/Buttons.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/NodeHeader.tsx
  src/components/map/RecentNodesList.tsx
  src/components/map/Sidebar/SearchInput.tsx
  src/components/map/Sidebar/SidebarNodeLink.tsx
  src/components/map/Sidebar/SidebarV2/ParentsChildrenSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ReferencesSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper2.tsx
  src/components/map/Sidebar/SidebarV2/TagsSidebar.tsx
  src/components/map/dashboard/DashboardStudents.tsx
  src/hooks/useTagsTreeView.ts
  src/knowledgeTypes.ts
  src/lib/utils/Map.utils.ts
  src/lib/utils/constants.ts
  src/lib/utils/develop.util.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/lib/utils/tutorials/nodeActionsTutorialStep.tsx
  src/lib/utils/tutorials/nodeConceptTutorialStep.tsx
  src/lib/utils/tutorials/nodeTutorialSteps.tsx
  src/lib/utils/tutorials/parentChildrenListTutorialSteps.tsx
  src/lib/utils/tutorials/searcherTutorialSteps.tsx
  src/lib/utils/tutorials/toolbooxTutorialSteps.tsx
  src/pages/api/searchNodes.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/notebook.tsx
  src/types.ts
  src/utils/dates.ts
Labels: bug, enhancement

#2243 merge to main
  cloud-functions/functions/src/index.ts
  src/client/firestore/mostUsedNodesByUser.firestore.ts
  src/client/firestore/recentUserNodes.firestore.ts
  src/components/map/Sidebar/SidebarV2/ReferencesSidebar.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2244 add defualt values on tag, parents and children sidebars
  src/client/firestore/mostUsedNodesByUser.firestore.ts
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ParentsChildrenSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ReferencesSidebar.tsx
  src/components/map/Sidebar/SidebarV2/TagsSidebar.tsx
  src/lib/utils/maps.utils.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/pages/notebook.tsx
  src/pages/notebooks/[title]/[id].tsx
Labels: bug, enhancement

#2245 Merge to main
  src/client/firestore/mostUsedNodesByUser.firestore.ts
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ParentsChildrenSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ReferencesSidebar.tsx
  src/components/map/Sidebar/SidebarV2/TagsSidebar.tsx
  src/lib/utils/maps.utils.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/pages/notebook.tsx
  src/pages/notebooks/[title]/[id].tsx
Labels: enhancement

#2247 Feature/add videos on interactive tutorial
  src/components/interactiveTutorial/TooltipTutorial.tsx
  src/components/tutorial/TutorialTableOfContent.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/constants.ts
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/knowledgeGraphSteps.tsx
  src/lib/utils/tutorials/nodeInteractionsSteps.tsx
  src/lib/utils/tutorials/nodeTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2248 merge to main
  src/components/interactiveTutorial/TooltipTutorial.tsx
  src/components/practiceTool/PracticeQuestion.tsx
  src/components/tutorial/TutorialTableOfContent.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/constants.ts
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/knowledgeGraphSteps.tsx
  src/lib/utils/tutorials/nodeActionsTutorialStep.tsx
  src/lib/utils/tutorials/nodeInteractionsSteps.tsx
  src/lib/utils/tutorials/nodeTutorialSteps.tsx
  src/lib/utils/tutorials/parentChildrenListTutorialSteps.tsx
  src/lib/utils/tutorials/pathwaysTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug

#2254 merge to main
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
Labels: bug

#2269 Custom Search option in searchNodesInNotebook api
  src/client/firestore/userNodes.firestore.ts
  src/pages/api/searchNodesInNotebook.ts
  src/pages/iframe.tsx
Labels: enhancement

#2262 fix error on get userNodes
  src/client/firestore/userNodes.firestore.ts
Labels: bug

#2271 Feature/improve interactive tutorials
  src/components/interactiveTutorial/TooltipTutorial.tsx
  src/components/map/Sidebar/UserDetails.tsx
  src/lib/utils/develop.util.ts
  src/lib/utils/tutorials/knowledgeGraphSteps.tsx
  src/lib/utils/tutorials/nodeActionsTutorialStep.tsx
  src/lib/utils/tutorials/nodeInteractionsSteps.tsx
  src/lib/utils/tutorials/nodeQuestionStepTutorialStep.tsx
  src/lib/utils/tutorials/nodeTutorialSteps.tsx
  src/lib/utils/tutorials/reconcilingProposalsTutorialSteps.tsx
  src/lib/utils/tutorials/searcherTutorialSteps.tsx
  src/lib/utils/tutorials/tutorial.utils.ts
  src/nodeBookTypes.ts
  src/pages/iframe.tsx
  src/pages/notebook.tsx
  src/pages/notebooks/[title]/[id].tsx
Labels: bug

#2276 fix build error
  src/components/home/HomeWrapper.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/userSettingsTutorialSteps.tsx
Labels: bug

#2279 Feature/improve interactive tutorials
  public/rive/ai.riv
  src/components/AppFooter.tsx
  src/components/Header/AppHeader.tsx
  src/components/Header/MenuHeader.tsx
  src/components/home/SectionsItems.tsx
  src/components/home/components/SectionWrapper.tsx
  src/components/home/sections/Hero.tsx
  src/components/home/sections/Mechanism.tsx
  src/components/home/sections/constants/valuesItems.ts
  src/components/interactiveTutorial/TooltipTutorial.tsx
  src/components/map/Node.tsx
  src/components/map/Sidebar/UserDetails.tsx
  src/hooks/useEventListener.ts
  src/hooks/useInteractiveTutorial3.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#2280 merge to main
  public/rive/ai.riv
  src/components/AppFooter.tsx
  src/components/Header/AppHeader.tsx
  src/components/Header/MenuHeader.tsx
  src/components/home/SectionsItems.tsx
  src/components/home/components/SectionWrapper.tsx
  src/components/home/sections/Hero.tsx
  src/components/home/sections/Mechanism.tsx
  src/components/home/sections/constants/valuesItems.ts
  src/components/interactiveTutorial/TooltipTutorial.tsx
  src/components/map/Node.tsx
  src/components/map/Sidebar/UserDetails.tsx
  src/hooks/useEventListener.ts
  src/hooks/useInteractiveTutorial3.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#2284 Feature/improve interactive tutorials
  src/components/assistant/mechanismItems.ts
  src/components/home/sections/Mechanism.tsx
Labels: bug

#2285 merge to main
  src/components/assistant/mechanismItems.ts
  src/components/home/sections/Mechanism.tsx
Labels: bug

#2286 Feature/improve interactive tutorials
  src/pages/notebook.tsx
Labels: bug

#2287 merge to main
  src/pages/notebook.tsx
Labels: bug

#2295 update ai animation
  public/rive/ai.riv
Labels: bug

#2296 merge to main
  public/rive/ai.riv
  src/pages/api/rateVersion.ts
  src/utils/version-helpers.ts
Labels: bug

#2301 advance improving home page
  src/components/Header/AppHeader.tsx
  src/components/assistant/sections.ts
  src/components/home/SectionsItems.tsx
  src/components/home/sections/Hero.tsx
Labels: enhancement

#2302 merge to main
  src/components/Header/AppHeader.tsx
  src/components/assistant/sections.ts
  src/components/home/SectionsItems.tsx
  src/components/home/sections/Hero.tsx
Labels: bug

#2311 Tmp/improve initial tooltip position
  src/components/interactiveTutorial/TooltipTutorial.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/livenessBarTutorialSteps.tsx
  src/lib/utils/tutorials/reconcilingProposalsTutorialSteps.tsx
  src/lib/utils/tutorials/searcherTutorialSteps.tsx
  src/lib/utils/tutorials/temporalTutorialSteps.tsx
  src/lib/utils/tutorials/toolbooxTutorialSteps.tsx
  src/lib/utils/tutorials/tutorial.utils.ts
  src/lib/utils/tutorials/userInfoTutorialSteps.tsx
  src/lib/utils/tutorials/userSettingsTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2326 Fix/testing notebook like new user
  src/components/map/Node.tsx
  src/components/map/QuestionChoices.tsx
  src/components/map/Sidebar/SidebarNodeLink.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/modals/CookiePolicy.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/proposalTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/api/assistant/generateQuestionNode.ts
  src/pages/api/signup.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2328 merge to main
  src/components/Editor.tsx
  src/components/map/Node.tsx
  src/components/map/QuestionChoices.tsx
  src/components/map/Sidebar/SidebarNodeLink.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/modals/CookiePolicy.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/knowledgeGraphSteps.tsx
  src/lib/utils/tutorials/proposalTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/api/assistant/generateQuestionNode.ts
  src/pages/api/signup.ts
  src/pages/notebook.tsx
Labels: bug

#2330 Fix/testing notebook like new user
  src/components/map/QuestionChoices.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/pages/api/assistant/generateQuestionNode.ts
  src/pages/api/assistant/getNotebooks.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2336 fix markdown render
  src/components/Editor.tsx
Labels: bug

#2338 render node titles as markdown when user zoom out
  src/components/map/Node.tsx
Labels: bug

#2349 Fix/display markdown and diff content on nodes
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/UserStatusIcon.tsx
  src/lib/reducers/nodeBook.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug

#2350 merge to main
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/UserStatusIcon.tsx
  src/lib/reducers/nodeBook.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#2353 Feature/improve tag searcher
  src/components/HomeFilter.tsx
  src/components/SignUpBasicInfo.tsx
  src/components/TagsSearcher.tsx
  src/components/map/Sidebar/SidebarV2/ParentsChildrenSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ReferencesSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/TagsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/components/map/UserStatusSettings2.tsx
  src/global.css
  src/hooks/useTraceUpdate.tsx
  src/pages/notebook.tsx
  src/styles/app.css
Labels: bug, enhancement

#2357 update tutorials
  src/components/TagsSearcher.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/pages/notebook.tsx
Labels: enhancement

#2369 Fix/after select proposal is not drawed correctly
  src/components/interactiveTutorial/TooltipTutorial.tsx
  src/components/map/Liveliness/ActionBubble.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/components/map/ProposalsList/ProposalItem/ProposalItem.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/hooks/useTraceUpdate.tsx
  src/pages/notebook.tsx
  src/utils/helpers.ts
Labels: bug, enhancement

#2371 merge to main
  src/components/interactiveTutorial/TooltipTutorial.tsx
  src/components/map/Liveliness/ActionBubble.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/components/map/ProposalsList/ProposalItem/ProposalItem.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/hooks/useTraceUpdate.tsx
  src/pages/notebook.tsx
  src/utils/helpers.ts
Labels: bug, enhancement

#2372 fix tags snapshot to update only when is required
  src/hooks/useTagsTreeView.ts
  src/hooks/useTraceUpdate.tsx
  src/hooks/userHover.ts
  src/lib/utils/develop.util.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/pages/notebook.tsx
  src/pages/notebooks/[title]/[id].tsx
  src/workers/MapWorker.ts
Labels: bug

#2373 merge to main
  src/hooks/useTagsTreeView.ts
  src/hooks/useTraceUpdate.tsx
  src/hooks/userHover.ts
  src/lib/utils/develop.util.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/pages/notebook.tsx
  src/pages/notebooks/[title]/[id].tsx
  src/workers/MapWorker.ts
Labels: bug

#2377 add hover and event to open proposals on last edited text
  src/components/map/NodeFooter.tsx
Labels: bug

#2376 remove start icon on proposal item
  src/components/map/ProposalsList/ProposalItem/ProposalItem.tsx
Labels: enhancement

#2380 Feature/open proposal when click on last edited text
  FrontendGuidelines.md
  __tests__/client/components/ErrorBoundary.test.tsx
  __tests__/client/utils/userStatus.utils.test.ts
  package.json
  src/client/firestore/errors.firestore.ts
  src/components/ErrorBoundary.tsx
  src/components/Header/AppHeader.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/components/map/Sidebar/ProfileAvatar.tsx
  src/components/map/dashboard/DashboardStudents.tsx
  src/lib/mapApi.ts
  src/lib/utils/customError.ts
  src/pages/_app.tsx
  src/pages/notebook.tsx
  src/styles/app.css
  src/types.ts
Labels: bug

#2383 fix tutorials on TOC
  src/lib/utils/tutorials/reconcilingProposalsTutorialSteps.tsx
  src/pages/notebook.tsx
Labels: bug

#2381 merge to main
  FrontendGuidelines.md
  __tests__/client/components/ErrorBoundary.test.tsx
  __tests__/client/utils/userStatus.utils.test.ts
  package.json
  src/client/firestore/errors.firestore.ts
  src/components/ErrorBoundary.tsx
  src/components/Header/AppHeader.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/ProposalsList/ProposalItem/ProposalItem.tsx
  src/components/map/Sidebar/ProfileAvatar.tsx
  src/components/map/dashboard/DashboardStudents.tsx
  src/lib/mapApi.ts
  src/lib/utils/customError.ts
  src/lib/utils/tutorials/reconcilingProposalsTutorialSteps.tsx
  src/pages/_app.tsx
  src/pages/notebook.tsx
  src/styles/app.css
  src/types.ts
Labels: bug, enhancement
