Repository ImanYZ/1Cademy-Public, pull requests merged in 2023-01, with the labels that each got.

#1107 added video start and time time option, updated node editor and removed vimeo option
  src/components/Editor.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/lib/utils/utils.ts
  src/nodeBookTypes.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/notebook.tsx
  src/types/INodeVersion.ts
Labels: enhancement

#1108 added video start and time time option, updated node editor and removed vimeo option
  src/components/Editor.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/lib/utils/utils.ts
  src/nodeBookTypes.ts
  src/pages/api/proposeChildNode.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/notebook.tsx
  src/types/INodeVersion.ts
Labels: enhancement

#1115 google map api key passed from cloudbuild
  cloudbuild.dev.yaml
  cloudbuild.yaml
Labels: enhancement

#1113 Feature/home page animation
  src/components/AppHeaderSearchBar.tsx
  src/components/home/views/HowItWorks.tsx
  src/pages/index.tsx
Labels: bug, enhancement

#1116 google api key cloudbuild settings
  Dockerfile
  cloudbuild.dev.yaml
  cloudbuild.yaml
Labels: enhancement

#1124 Feature/home page to assistant module
  public/assistant/robot.png
  public/rive-assistant/part2.riv
  public/rive-assistant/primera.riv
  public/rive-assistant/tercera.riv
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/sectionsOrder.ts
  src/components/assistant/whyItems.ts
  src/pages/assistant.tsx
Labels: enhancement

#1130 Feature/home page to assistant module
  public/assistant/1-climing-and-helping.svg
  public/assistant/10-uses-scientifically-proven.svg
  public/assistant/11-leverages-methods.svg
  public/assistant/12-prospect-therory.svg
  public/assistant/2-auto-schedule.svg
  public/assistant/4-is-in-sync.svg
  public/assistant/5-ai-assistant.svg
  public/assistant/6-schedule-task.svg
  public/assistant/7-signals-how-close.svg
  public/assistant/8-motivates-through.svg
  public/assistant/9-allows-you-to-easily-modify.svg
  public/rive-assistant/assistant-1.riv
  public/rive-assistant/assistant-3.riv
  public/rive-assistant/meetings.riv
  src/components/AppHeaderSearchBar.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
  src/lib/theme/brandingTheme.ts
  src/pages/assistant.tsx
  src/pages/index.tsx
  src/styles/custom.css
Labels: bug, enhancement

#1132 Feature/home page to assistant module
  public/rive-assistant/assistant-1.riv
  src/components/assistant/sectionsOrder.ts
  src/pages/assistant.tsx
Labels: bug, enhancement

#1131 merge develop to main
  public/assistant/1-climing-and-helping.svg
  public/assistant/10-uses-scientifically-proven.svg
  public/assistant/11-leverages-methods.svg
  public/assistant/12-prospect-therory.svg
  public/assistant/2-auto-schedule.svg
  public/assistant/4-is-in-sync.svg
  public/assistant/5-ai-assistant.svg
  public/assistant/6-schedule-task.svg
  public/assistant/7-signals-how-close.svg
  public/assistant/8-motivates-through.svg
  public/assistant/9-allows-you-to-easily-modify.svg
  public/assistant/robot.png
  public/rive-assistant/assistant-1.riv
  public/rive-assistant/assistant-2.riv
  public/rive-assistant/assistant-3.riv
  public/rive-assistant/meetings.riv
  src/components/AppHeaderSearchBar.tsx
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/sectionsOrder.ts
  src/components/assistant/whyItems.ts
  src/components/home/components/TableOfContent.tsx
  src/lib/theme/brandingTheme.ts
  src/pages/assistant.tsx
  src/pages/index.tsx
  src/styles/custom.css
Labels: bug, enhancement

#1133 Feature/home page to assistant module
  public/assistant/1-climing-and-helping.svg
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
Labels: bug, enhancement

#1134 improve assistant Home page
  public/assistant/1-climing-and-helping.svg
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
Labels: bug, enhancement

#1135 scroll to new node is fixed
  src/pages/notebook.tsx
Labels: enhancement

#1136 scroll to new node is fixed
  src/pages/notebook.tsx
Labels: enhancement

#1138 removed word free
  src/components/assistant/whyItems.ts
Labels: bug

#1139 fix word in why section from assistant home page
  src/components/assistant/whyItems.ts
Labels: bug

#1140 Feature/assistant home page dark mode
  public/assistant/10-uses-scientifically-proven-dark.svg
  public/assistant/11-leverages-methods-dark.svg
  public/assistant/12-prospect-therory-dark.svg
  public/assistant/6-schedule-task-dark.svg
  public/rive-assistant/assistant-1.riv
  public/rive-assistant/assistant-2.riv
  public/rive-assistant/assistant-3.riv
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
  src/pages/assistant.tsx
Labels: bug, enhancement

#1141 darkmode assistant homepage
  public/assistant/10-uses-scientifically-proven-dark.svg
  public/assistant/11-leverages-methods-dark.svg
  public/assistant/12-prospect-therory-dark.svg
  public/assistant/6-schedule-task-dark.svg
  public/rive-assistant/assistant-1.riv
  public/rive-assistant/assistant-2.riv
  public/rive-assistant/assistant-3.riv
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
  src/pages/assistant.tsx
Labels: bug, enhancement

#1142 add meeting item ind dark mode
  public/rive-assistant/meetings.riv
  src/components/assistant/Why.tsx
Labels: enhancement

#1143 merge develop to main
  public/assistant/1-climing-and-helping.svg
  public/assistant/10-uses-scientifically-proven-dark.svg
  public/assistant/10-uses-scientifically-proven.svg
  public/assistant/2-auto-schedule.svg
  public/assistant/4-is-in-sync.svg
  public/assistant/5-ai-assistant-dark.svg
  public/assistant/5-ai-assistant.svg
  public/rive-assistant/meetings.riv
  src/components/AppHeaderSearchBar.tsx
  src/components/SearcherPupUp.tsx
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
  src/components/home/views/Values.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/Node.tsx
  src/pages/assistant.tsx
  src/pages/index.tsx
Labels: enhancement

#1148 Feature/assistant home page dark mode
  public/rive-assistant/assistant-0.riv
  public/rive-assistant/assistant-1.riv
  public/rive-assistant/assistant-2.riv
  public/rive-assistant/assistant-3.riv
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/sectionsOrder.ts
  src/components/home/components/TableOfContent.tsx
  src/pages/assistant.tsx
  src/pages/index.tsx
Labels: enhancement

#1151 add background and text in hero section
  public/rive-assistant/assistant-0.riv
  public/rive-assistant/assistant-2.riv
  src/pages/assistant.tsx
Labels: bug

#1152 merge develop to main
  public/rive-assistant/assistant-0.riv
  public/rive-assistant/assistant-2.riv
  src/pages/assistant.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#1153 Feature/improve home page
  public/rive-assistant/assistant-0.riv
  public/rive-assistant/assistant-1.riv
  public/rive-assistant/assistant-2.riv
  public/rive-assistant/assistant-3.riv
  public/rive-assistant/meetings.riv
  src/pages/assistant.tsx
  src/pages/index.tsx
Labels: bug

#1154 merge develop to main
  public/rive-assistant/assistant-0.riv
  public/rive-assistant/assistant-1.riv
  public/rive-assistant/assistant-2.riv
  public/rive-assistant/assistant-3.riv
  public/rive-assistant/meetings.riv
  src/pages/assistant.tsx
  src/pages/index.tsx
Labels: bug

#1189 Feature/add infinite loader in sidebars
  src/components/map/Sidebar/BookmarksList.tsx
  src/components/map/Sidebar/NotificationsList.tsx
  src/components/map/Sidebar/PendingProposalList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/hooks/useObserver.ts
Labels: enhancement

#1190 Feature/add chips in public searcher
  src/components/HomeFilter.tsx
Labels: enhancement

#1202 fix links in what section
  src/components/home/views/What.tsx
Labels: bug

#1207 Feature/improve why section showing items in rows
  public/static/Balanced_Perspectives.svg
  public/static/Evaluating.old.svg
  public/static/Evaluating.svg
  public/static/Improving.old.svg
  public/static/Improving.svg
  public/static/Learning_Deeply.old.svg
  public/static/Learning_Deeply.svg
  public/static/Learning_Through_Teaching.svg
  public/static/Research_Communities.svg
  public/static/Search_for_Learning.svg
  src/components/assistant/Why.tsx
  src/components/home/components/UniversitiesMap/UniversitiesMap.tsx
  src/components/home/views/Values.tsx
  src/components/home/views/What.tsx
  src/components/home/views/WhoWeAre.tsx
  src/components/home/views/communitiesOrder.tsx
  src/components/home/views/valuesItems.ts
  src/hooks/useMultipleObserver.ts
  src/hooks/useObserver.ts
  src/pages/assistant.tsx
  src/pages/index.tsx
  src/styles/animations.css
Labels: enhancement

#1203 merge develop to main
  public/LibraryBackgroundLighter.jpg
  public/rive/artboard-3.riv
  public/rive/artboard-4.riv
  public/rive/artboard-5.riv
  public/rive/artboard-6.riv
  public/rive/scroll.riv
  public/static/Balanced_Perspectives.svg
  public/static/Evaluating.old.svg
  public/static/Evaluating.svg
  public/static/Improving.old.svg
  public/static/Improving.svg
  public/static/Learning_Deeply.old.svg
  public/static/Learning_Deeply.svg
  public/static/Learning_Through_Teaching.svg
  public/static/Research_Communities.svg
  public/static/Search_for_Learning.svg
  src/components/HomeFilter.tsx
  src/components/ThemeSwitcher.tsx
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
  src/components/home/components/UniversitiesMap/UniversitiesMap.tsx
  src/components/home/views/HowItWorks.tsx
  src/components/home/views/Values.tsx
  src/components/home/views/What.tsx
  src/components/home/views/WhoWeAre.tsx
  src/components/home/views/communitiesOrder.tsx
  src/components/home/views/valuesItems.ts
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/Sidebar/BookmarksList.tsx
  src/components/map/Sidebar/NotificationsList.tsx
  src/components/map/Sidebar/PendingProposalList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/hooks/useMultipleObserver.ts
  src/hooks/useObserver.ts
  src/pages/assistant.tsx
  src/pages/index.tsx
  src/pages/notebook.tsx
  src/styles/animations.css
Labels: bug, enhancement

#1209 merge develop to main
  public/static/Learning_Deeply-dark.svg
  public/static/Learning_Like_Researchers.old.svg
  public/static/Learning_Like_Researchers.old2.svg
  public/static/Learning_Like_Researchers.svg
  public/static/Learning_Through_Teaching-dark.svg
  public/static/Search_for_Learning-dark.svg
  src/components/home/views/Values.tsx
  src/components/home/views/valuesItems.ts
  src/pages/index.tsx
Labels: bug, enhancement

#1223 add new illustrations
  public/static/Learning_Deeply-dark.svg
  public/static/Learning_Deeply.svg
  public/static/Learning_Through_Teaching-dark.old.svg
  public/static/Learning_Through_Teaching-dark.svg
  public/static/Learning_Through_Teaching-old.svg
  public/static/Learning_Through_Teaching.svg
  public/static/Search_for_Learning-dark.svg
  public/static/Search_for_Learning.svg
Labels: bug, enhancement

#1240 Improvements from Develop
  package-lock.json
  package.json
  public/static/Dark_Learning_Like_Researchers.svg
  public/static/Learning_Deeply-dark.svg
  public/static/Learning_Deeply.svg
  public/static/Learning_Like_Researchers.old2.svg
  public/static/Learning_Like_Researchers.svg
  public/static/Learning_Through_Teaching-dark.old.svg
  public/static/Learning_Through_Teaching-dark.svg
  public/static/Learning_Through_Teaching-old.svg
  public/static/Learning_Through_Teaching.svg
  public/static/Light_Learning_Like_Researchers.svg
  public/static/Search_for_Learning-dark.svg
  public/static/Search_for_Learning.svg
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
  src/components/home/views/Values.tsx
  src/components/home/views/valuesItems.ts
  src/components/map/FocusedNotebook/FocusedLinkedNodes.tsx
  src/components/map/FocusedNotebook/FocusedNotebook.tsx
  src/components/map/LinkingWords/ReferenceLabelInput.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/Sidebar/SidebarV2/CitationsSidebar.tsx
  src/global.css
  src/pages/_app.tsx
  src/pages/assistant.tsx
  src/pages/index.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#1244 merge to main
  package-lock.json
  package.json
  public/random.jpg
  public/rive-assistant/assistant-1.riv
  public/rive-assistant/assistant-2.riv
  public/rive-assistant/assistant-3.riv
  public/rive-assistant/goals.riv
  public/rive/animation.riv
  public/rive/artboard-4.riv
  public/rive/extension.riv
  public/rive/notebook.riv
  public/static/Evaluating-dark.svg
  public/static/Evaluating.svg
  public/static/Learning_Deeply-dark.svg
  public/static/Learning_Deeply.svg
  public/static/Learning_Through_Teaching-old.svg
  public/static/Learning_Through_Teaching.svg
  public/static/Research_Communities.svg
  src/components/assistant/HowItWorks.tsx
  src/components/home/components/temporals/RiveComponentExtended.tsx
  src/components/home/components/temporals/useRiveMemoized.tsx
  src/components/home/sectionsOrder.ts
  src/components/home/views/HowItWorks.tsx
  src/components/home/views/Which.tsx
  src/components/home/views/valuesItems.ts
  src/components/home/views/whichValues.ts
  src/pages/assistant.tsx
  src/pages/index.tsx
Labels: enhancement

#1250 Fix/imrpove home page code
  public/rive-assistant/assistant-3.riv
  public/rive-assistant/goals.riv
  public/static/Crowdsourcing.old.png
  public/static/Crowdsourcing.svg
  src/components/assistant/HowItWorks.tsx
  src/components/assistant/Why.tsx
  src/components/assistant/sectionsOrder.ts
  src/components/home/components/Magnitude.tsx
  src/components/home/views/HowItWorks.tsx
  src/components/home/views/Which.tsx
  src/components/home/views/valuesItems.ts
  src/components/home/views/whichValues.ts
  src/knowledgeTypes.ts
  src/lib/utils/RE.ts
  src/pages/assistant.tsx
  src/pages/index.tsx
  src/styles/animations.css
Labels: bug, enhancement

#1254 Fix/imrpove home page code
  public/rive-assistant/assistant-2.riv
  public/rive-assistant/assistant-3.riv
  public/rive/extension.riv
  src/components/assistant/HowItWorks.tsx
  src/components/home/components/Magnitude.tsx
  src/components/home/views/Which.tsx
  src/components/home/views/whichValues.ts
  src/styles/animations.css
Labels: bug, enhancement

#1255 Fix/imrpove home page code
  public/static/Crowdsourcing.old.png
  public/static/Developing_Learning_Pathways_dark.svg
  public/static/Developing_Learning_Pathways_light.svg
  public/static/Improving.svg
  public/static/Search_for_Learning-dark.svg
  public/static/Search_for_Learning.svg
  src/components/assistant/HowItWorks.tsx
  src/components/home/views/valuesItems.ts
Labels: bug

#1256 merge to main
  public/static/Crowdsourcing.old.png
  public/static/Developing_Learning_Pathways_dark.svg
  public/static/Developing_Learning_Pathways_light.svg
  public/static/Improving.svg
  public/static/Search_for_Learning-dark.svg
  public/static/Search_for_Learning.svg
  src/components/assistant/HowItWorks.tsx
  src/components/home/views/valuesItems.ts
Labels: enhancement

#1261 Feature/add assistant form
  src/components/assistant/AssistantRegister.tsx
  src/pages/assistant.tsx
Labels: enhancement

#1262 merge to main
  src/components/assistant/AssistantRegister.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/pages/assistant.tsx
Labels: enhancement

#1264 improve backgrounds
  src/components/assistant/AssistantRegister.tsx
  src/pages/assistant.tsx
Labels: enhancement

#1265 merge to main
  src/components/assistant/AssistantRegister.tsx
  src/pages/assistant.tsx
Labels: enhancement

#1274 Fix/scroll jump when modify filters in search page
  src/components/AppFooter.tsx
  src/components/AppFooter2.tsx
  src/components/AppHeader.tsx
  src/components/AppHeaderNavbar.tsx
  src/components/AppHeaderSearchBar.tsx
  src/components/CustomPagination.tsx
  src/components/HomeFilter.tsx
  src/components/HomeSearch.tsx
  src/components/LinkedNodes.tsx
  src/components/PagesNavbar.tsx
  src/components/SearchInput.tsx
  src/components/SearcherPupUp.tsx
  src/components/SortByFilters.tsx
  src/components/TypographyUnderlined.tsx
  src/global.css
  src/lib/utils/navbarSections.ts
  src/pages/assistant.tsx
  src/pages/home.tsx
  src/pages/index.tsx
  src/pages/node/[title]/[id].tsx
  src/pages/search.tsx
Labels: bug, enhancement

#1275 fix icons in header
  src/components/AppHeader.tsx
  src/components/NodeItemFullSkeleton.tsx
  src/components/PagesNavbar.tsx
  src/pages/assistant.tsx
  src/pages/home.tsx
Labels: bug, enhancement

#1277 Fix/assistant form responsiveness
  public/static/Balanced_Perspectives.svg
  public/static/Balanced_Perspectives_Dark.svg
  public/static/Balanced_Perspectives_Ligth.svg
  src/components/AppHeader.tsx
  src/components/assistant/AssistantRegister.tsx
  src/components/home/views/valuesItems.ts
  src/pages/assistant.tsx
Labels: bug, enhancement

#1283 add extension link
  src/components/home/views/whichValues.ts
Labels: enhancement

#1284 merge to main
  src/components/home/views/whichValues.ts
Labels: enhancement

#1286 add schedule images
  public/assistant/3-schedules-your-1-to-1-and-group-meetings-dark.svg
  public/assistant/3-schedules-your-1-to-1-and-group-meetings-light.svg
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
Labels: enhancement

#1287 merge to main
  public/assistant/3-schedules-your-1-to-1-and-group-meetings-dark.svg
  public/assistant/3-schedules-your-1-to-1-and-group-meetings-light.svg
  src/components/assistant/Why.tsx
  src/components/assistant/whyItems.ts
Labels: enhancement

#1297 fixed voting concurrency on nodes and node versions
  __tests__/pages/api/correctNode.test.ts
  __tests__/pages/api/rateVersion.concurrency.test.ts
  __tests__/pages/api/wrongNode.test.ts
  __tests__/utils/upDownVoteNode/upDownVoteNode.concurrency.test.ts
  src/lib/firestoreServer/admin.ts
  src/pages/api/correctNode/[nodeId].ts
  src/pages/api/rateVersion.ts
  src/pages/api/wrongNode/[nodeId].ts
  src/utils/baseReputationObj.ts
  src/utils/deleteTagCommunityAndTagsOfTags.ts
  src/utils/tagsAndCommPoints.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: enhancement

#1298 Enhancements from develop
  __tests__/pages/api/correctNode.test.ts
  __tests__/pages/api/rateVersion.concurrency.test.ts
  __tests__/pages/api/wrongNode.test.ts
  __tests__/utils/upDownVoteNode/upDownVoteNode.concurrency.test.ts
  src/components/home/views/communitiesOrder.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/knowledgeTypes.ts
  src/lib/firestoreClient/auth.ts
  src/lib/firestoreServer/admin.ts
  src/pages/api/correctNode/[nodeId].ts
  src/pages/api/rateVersion.ts
  src/pages/api/wrongNode/[nodeId].ts
  src/pages/notebook.tsx
  src/utils/baseReputationObj.ts
  src/utils/deleteTagCommunityAndTagsOfTags.ts
  src/utils/tagsAndCommPoints.ts
  src/utils/upDownVoteNode.ts
  src/utils/version-helpers.ts
Labels: enhancement

#1307 Improvements from develop
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/Node.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/pages/api/signup.ts
  src/pages/notebook.tsx
Labels: enhancement
