Repository ImanYZ/1Cademy-Public, pull requests merged in 2023-03, with the labels that each got.

#1469 Feature/improve tutorial by last feedback
  src/components/map/Node.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/global.css
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/reducers/nodeTutorial2.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#1473 Feature/improve animation of target element in tutorial
  src/styles/app.css
Labels: enhancement

#1464 Improvements from develop to main
  src/components/Editor.tsx
  src/components/map/LinkingWords/LinkingButton.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/Node/NodeTypeSelector.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SidebarWrapper.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/global.css
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/reducers/nodeTutorial2.tsx
  src/lib/reducers/searcherTutorial.tsx
  src/lib/utils/Map.utils.ts
  src/lib/utils/interactiveTutorialNodes.tsx
  src/lib/utils/nodesSyncronization.utils.ts
  src/lib/utils/tutorials/proposalSteps.tsx
  src/lib/utils/tutorials/tutorial.utils.ts
  src/nodeBookTypes.ts
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/notebook.tsx
  src/styles/app.css
Labels: bug

#1475 change tooltip tutorial UI styles
  src/components/interactiveTutorial/Tutorial.tsx
  src/lib/reducers/nodeTutorial2.tsx
Labels: enhancement

#1478 merge last improvement from dev to main
  src/components/interactiveTutorial/Tutorial.tsx
  src/lib/reducers/nodeTutorial2.tsx
Labels: enhancement

#1479 point in the last step onto the pending list on toolbar
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/lib/utils/tutorials/proposalSteps.tsx
Labels: enhancement

#1480 dev to main
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/lib/utils/tutorials/proposalSteps.tsx
Labels: enhancement

#1484 notebook error on changing reference
  src/pages/notebook.tsx
Labels: enhancement

#1485 notebook error on add/edit reference
  src/pages/notebook.tsx
Labels: enhancement

#1493 delete node fixed on downvote
  src/pages/notebook.tsx
Labels: bug

#1491 Height simulation on Editor open
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1494 Notebook callbacks optimization and sNode bugfix
  src/pages/notebook.tsx
Labels: enhancement

#1495 Improvements from develop
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodeHeader.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/reducers/nodeTutorial2.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
  src/styles/app.css
Labels: bug, enhancement

#1501 node type updates to parent and children
  src/lib/utils/proposalSummariesGenerator.ts
  src/pages/api/proposeNodeImprovement.ts
  src/utils/version-helpers.ts
Labels: enhancement

#1507 on hiding Node change visible status in parents that are opened already
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1508 Improvements from Develop
  public/lightModeLibraryBackground.png
  src/components/home/components/SectionItemSwitcher.tsx
  src/components/home/sections/Papers.tsx
  src/components/layouts/AuthLayout.tsx
  src/components/map/LinksList.tsx
  src/components/map/Node.tsx
  src/lib/utils/proposalSummariesGenerator.ts
  src/nodeBookTypes.ts
  src/pages/api/proposeNodeImprovement.ts
  src/pages/notebook.tsx
  src/styles/app.css
  src/utils/version-helpers.ts
Labels: bug, enhancement

#1512 Notebook hide node issue
  src/pages/notebook.tsx
Labels: enhancement

#1515 Notebook performance improvement
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/global.css
  src/hooks/useWorkerQueue.tsx
  src/lib/utils/Map.utils.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1513 Improvements from develop
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/global.css
  src/hooks/useWorkerQueue.tsx
  src/lib/utils/Map.utils.ts
  src/lib/utils/nodesSyncronization.utils.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1518 Wrong node interaction callback
  src/pages/notebook.tsx
Labels: enhancement

#1519 Wrong node interaction callback
  src/pages/notebook.tsx
Labels: bug

#1520 Note re-render on correct vote request complete
  src/pages/notebook.tsx
Labels: enhancement

#1521 Node re-render on correct vote request complete
  src/pages/notebook.tsx
Labels: enhancement

#1523 Notebook re-render on reloading permanent graph
  src/pages/notebook.tsx
Labels: enhancement

#1526 reloading of permanent graph fixed
  src/pages/notebook.tsx
Labels: enhancement

#1527 reloading of permanent graph fixed
  public/rive-tutorial/panning.riv
  public/rive-tutorial/zooming.riv
  src/components/Markdown/Markdown_Proposed.tsx
  src/components/home/components/temporals/RiveComponentExtended.tsx
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/CommunityLeaderboard/CommunityLeaderboard.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ProposalsSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/tutorial/ProgressBar.tsx
  src/components/tutorial/TutorialTableOfContent.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/hooks/useWorkerQueue.tsx
  src/lib/reducers/nodeTutorial2.tsx
  src/lib/utils/Map.utils.ts
  src/lib/utils/nodeTutorialSteps.tsx
  src/lib/utils/tutorials/childrenProposalTutorialStep.tsx
  src/lib/utils/tutorials/navigationTutorialSteps.tsx
  src/lib/utils/tutorials/nodeActionsTutoriialStep.tsx
  src/lib/utils/tutorials/nodeTutorialSteps.tsx
  src/lib/utils/tutorials/nodetypeTutorialSteps.tsx
  src/lib/utils/tutorials/proposalSteps.tsx
  src/lib/utils/tutorials/proposalTutorialSteps.tsx
  src/lib/utils/tutorials/reconcilingProposalsTutorialSteps.tsx
  src/lib/utils/tutorials/searcherTutorialSteps.tsx
  src/lib/utils/tutorials/tutorial.utils.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
  src/workers/MapWorker.ts
Labels: enhancement

#1537 Notebook performance improved
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/UserStatusIcon.tsx
  src/hooks/useWorkerQueue.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#1538 Notebook performance improved
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
Labels: enhancement

#1539 Link updates fixed on notebook
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1540 Edge removal logic updated during worker queue
  src/hooks/useWorkerQueue.tsx
Labels: enhancement

#1556 Improvements from develop
  public/lightModeLibraryBackground.png
  public/lightModeLibraryBackground_old.png
  public/share-light.svg
  public/share.svg
  src/components/NodeItem.tsx
  src/components/NodeItemDashboard.tsx
  src/components/NodeItemFull.tsx
  src/components/NodeVotes.tsx
  src/components/community/JoinUs.tsx
  src/components/community/PDFView.tsx
  src/components/community/UploadButton.tsx
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/FocusedNotebook/FocusedLinkedNodes.tsx
  src/components/map/FocusedNotebook/FocusedNodeContributors.tsx
  src/components/map/FocusedNotebook/FocusedNotebook.tsx
  src/components/map/FocusedNotebook/FocusedTagsList.tsx
  src/components/map/FocusedNotebook/HeadlessLeaderboardChip.tsx
  src/components/map/LinkingWords/LinkingButton.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/Node.tsx
  src/components/map/NodeFooter.tsx
  src/components/map/NodesList.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/SidebarV2/UserSettigsSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/components/map/UserStatusIcon.tsx
  src/components/tutorial/TutorialTableOfContent.tsx
  src/global.css
  src/hooks/useWorkerQueue.tsx
  src/lib/theme/brandingTheme.ts
  src/lib/utils/tutorials/nodetypeTutorialSteps.tsx
  src/lib/utils/tutorials/reconcilingProposalsTutorialSteps.tsx
  src/pages/community/[commIdx].tsx
  src/pages/home.tsx
  src/pages/instructors/dashboard/[uname].tsx
  src/pages/notebook.tsx
Labels: enhancement

#1578 Improvements from develop
  public/focus-dark.svg
  public/focus.svg
  public/toolbox-dark.svg
  public/toolbox-open.svg
  public/toolbox.svg
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/global.css
  src/pages/notebook.tsx
  src/styles/ComLeaderboard.css
Labels: enhancement

#1581 updated baseurl of node url for Sitemap
  src/lib/utils/1cademyConfig.ts
  src/lib/utils/utils.ts
Labels: enhancement

#1596 add focus mode tutorial
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/toolbooxTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1599 Feaure/redraw graph tutorial
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/toolbooxTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1607 update nodes children step in proposal tutorial + add trigger to remo…
  src/components/map/Node.tsx
  src/lib/utils/tutorials/nodeTutorialSteps.tsx
  src/lib/utils/tutorials/proposalTutorialSteps.tsx
  src/pages/notebook.tsx
  src/styles/app.css
Labels: enhancement

#1611 Feature/improve toc by last feedback
  src/components/tutorial/TutorialTableOfContent.tsx
  src/lib/utils/tutorials/grouptutorials.ts
Labels: bug

#1617 Feature/implement upvote tutorial
  src/components/tutorial/TutorialTableOfContent.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/nodeActionsTutorialStep.tsx
  src/lib/utils/tutorials/temporalTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1619 save in DB forced tutorials
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/tutorial/TutorialTableOfContent.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#1616 merge to main
  public/narrate-node-speak.svg
  public/narrate-node-stop-dark.svg
  public/narrate-node-stop-light.svg
  public/toolbox-dark-open.svg
  src/components/NodeItemFull.tsx
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/FocusedNotebook/FocusedNodeContributors.tsx
  src/components/map/FocusedNotebook/FocusedNotebook.tsx
  src/components/map/FocusedNotebook/FocusedRelatedNodes.tsx
  src/components/map/FocusedNotebook/FocusedTagsList.tsx
  src/components/map/LinkingWords/LinkingWords.tsx
  src/components/map/Node.tsx
  src/components/map/Node/NodeTypeSelector.tsx
  src/components/map/NodeFooter.tsx
  src/components/tutorial/TutorialTableOfContent.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/Map.utils.ts
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/nodeActionsTutorialStep.tsx
  src/lib/utils/tutorials/nodeTutorialSteps.tsx
  src/lib/utils/tutorials/proposalTutorialSteps.tsx
  src/lib/utils/tutorials/temporalTutorialSteps.tsx
  src/lib/utils/tutorials/toolbooxTutorialSteps.tsx
  src/lib/utils/tutorials/tutorial.utils.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
  src/styles/app.css
Labels: bug, enhancement

#1630 Feature/implement Hide tutorial
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/nodeActionsTutorialStep.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#1631 merge to main
  src/components/interactiveTutorial/Tutorial.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/nodeActionsTutorialStep.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#1649 Fix/notebook tutorial
  src/components/interactiveTutorial/Tutorial.tsx
  src/lib/utils/tutorials/childrenProposalTutorialStep.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/pages/notebook.tsx
Labels: bug

#1657 Fix issues uploading the resume and the transcript in the apply section
  src/components/community/JoinUs.tsx
  src/components/community/UploadButton.tsx
Labels: bug

#1665 Feature/change offsprings to decendant
  src/components/map/Node.tsx
  src/components/map/NodeHeader.tsx
  src/components/map/NodesList.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/Map.utils.ts
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/navigationTutorialSteps.tsx
  src/lib/utils/tutorials/nodeActionsTutorialStep.tsx
  src/lib/utils/tutorials/reconcilingProposalsTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1671 Feature/implement notifications tutorial
  src/components/map/Sidebar/SidebarV2/NotificationSidebar.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/notificationsTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: bug, enhancement

#1675 Feauture/implement bookmars tutorial
  src/components/map/Sidebar/SidebarV2/BookmarksSidebar.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/bookmarksTutorialSteps.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1680 implement leaderboard tutorial
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/components/map/Sidebar/UsersStatusList.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/leaderBoardTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1683 Feature/setup user info tutorial
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/Sidebar/SidebarV2/UserInfoSidebar.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/userInfoTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1684 Feauture/implement liveness bar
  src/components/map/Liveliness/LivelinessBar.tsx
  src/components/map/Liveliness/ReputationBar.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/leaderBoardTutorialSteps.tsx
  src/lib/utils/tutorials/livenessBarTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1686 implement community leaderboard tutorial
  src/components/map/CommunityLeaderboard/CommunityLeaderboard.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/communityLeaderBoardTutorialSteps.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1697 Feature/improve tutorials in mobile view
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/Sidebar/SidebarV2/PendingProposalSidebar.tsx
  src/components/map/Sidebar/SidebarV2/SearcherSidebar.tsx
  src/components/map/Sidebar/SidebarV2/ToolbarSidebar.tsx
  src/lib/utils/tutorials/leaderBoardTutorialSteps.tsx
  src/lib/utils/tutorials/pendingProposalsTutorial.tsx
  src/lib/utils/tutorials/searcherTutorialSteps.tsx
  src/lib/utils/tutorials/userInfoTutorialSteps.tsx
  src/lib/utils/tutorials/userSettingsTutorialSteps.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#1705 Feature/list parent children nodes tutorial
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/map/Node.tsx
  src/components/map/NodesList.tsx
  src/hooks/useInteractiveTutorial3.tsx
  src/lib/utils/tutorials/grouptutorials.ts
  src/lib/utils/tutorials/parentChildrenListTutorialSteps.tsx
  src/lib/utils/tutorials/temporalTutorialSteps.tsx
  src/nodeBookTypes.ts
  src/pages/notebook.tsx
Labels: enhancement

#1719 Feature/add progrees bar in next tutorial step
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/tutorial/ProgressBarMenu.tsx
  src/components/tutorial/TutorialTableOfContent.tsx
  src/pages/notebook.tsx
Labels: enhancement

#1720 merge to main
  src/components/interactiveTutorial/Tutorial.tsx
  src/components/tutorial/ProgressBarMenu.tsx
  src/components/tutorial/TutorialTableOfContent.tsx
  src/pages/notebook.tsx
Labels: bug, enhancement

#1725 Feature/update homepages
  src/components/assistant/Mechanism.tsx
  src/components/home/SectionsItems.tsx
  src/components/home/sections/Hero.tsx
  src/components/home/sections/Mechanism.tsx
Labels: enhancement
